Repository Pycord-Development/pycord, pull requests merged in 2021-10, with the labels that each got.

#183 Add `can_send` method to Messageable
  discord/abc.py
Labels: status: awaiting review

#341 Add example for slash commands in cogs.
  examples/app_commands/slash_cog.py
Labels: documentation, status: in progress, status: awaiting review

#118 Use full name for commands.Bot reference
  discord/bot.py
Labels: documentation, status: planned

#356 Return Interaction object in send_message
  discord/interactions.py
Labels: priority: low, status: awaiting review, feature

#344 Add additionally flags
  discord/enums.py
  discord/flags.py
  discord/guild.py
  docs/api.rst
Labels: documentation, status: awaiting review
