Repository Pycord-Development/pycord, pull requests merged in 2021-11, with the labels that each got.

#362 Update slash_perms.py example
  examples/app_commands/slash_perms.py
Labels: documentation

#364 Add an example with Buttons to self-assign roles
  examples/views/button_roles.py
Labels: documentation, status: awaiting review

#366 Fix Issue 363 and Implement Thread Query on WebhookMessage Classes
  discord/webhook/async_.py
  discord/webhook/sync.py
Labels: bug, priority: medium, status: awaiting review, feature

#348 Add utils.basic_autocomplete
  discord/utils.py
Labels: priority: medium, status: in progress, feature

#368 More Activities
  discord/enums.py
  docs/api.rst
Labels: help wanted, priority: low, status: in progress, feature

#360 Make ext.commands.help filter only prefixed commands.
  discord/ext/commands/help.py
Labels: bug, priority: high, status: awaiting review

#336 Implement discord.utils.generate_snowflake
  discord/object.py
  discord/utils.py
  docs/api.rst
Labels: status: awaiting review, feature

#233 Fix help command in cogs
  discord/cog.py
Labels: bug, priority: medium, status: planned

#377 [ci skip] pycord.dev and a few fixes
  README.rst
Labels: documentation, status: awaiting review

#378 Add DCO & Contributing
  CONTRIBUTING.md
  DEVELOPER_CERTIFICATE_OF_ORIGIN.md
Labels: priority: medium

#376 Add guild feature
  discord/guild.py
Labels: documentation

#379 Update Japanese Readme
  README.ja.rst
Labels: documentation

#382 Quick fix of japanese readme
  README.ja.rst
Labels: priority: high, bypass-review

#361 Add AutocompleteContext for autocomplete callbacks
  discord/commands/commands.py
  discord/commands/context.py
  discord/utils.py
Labels: priority: high, status: in progress, feature

#385 Merge autocomplete into master
  discord/commands/commands.py
  discord/commands/context.py
  discord/utils.py
Labels: priority: medium, status: awaiting review, feature

#386 Add examples to the `This PR is not a code change (e.g. documentation, README, typehinting, ...)`
  .github/PULL_REQUEST_TEMPLATE.md
Labels: priority: low, status: awaiting review

#332 Update intents for message intent becoming privileged
  discord/flags.py
  docs/intents.rst
Labels: priority: low, status: planned, feature

#390 Fix message content intent
  discord/flags.py
Labels: documentation

#409 Fix discord link
  docs/conf.py
Labels: documentation, priority: high

#421 Add Channel Banner Feature Flag
  discord/guild.py
Labels: documentation, priority: low

#131 Add transparent color
  discord/colour.py
Labels: priority: low, feature

#83 GitHub Action to run a security scan using bandit
  .github/workflows/bandit.yml
Labels: status: awaiting review, feature

#81 GitHub Action to run mypy on Python type hints
  .github/workflows/mypy.yml
Labels: status: awaiting review, feature

#408 Change http gateway version
  discord/http.py
Labels: priority: high, dependencies

#431 Add more Actions for CI/CD to check PRs & commits
  .github/workflows/bandit.yml
  .github/workflows/mypy.yml
Labels: priority: medium, status: in progress

#309 Support responding with deferred_channel_message to component interactions.
  discord/interactions.py
Labels: priority: low, status: in progress, feature

#395 Implement `bot.get_application_command`
  discord/bot.py
Labels: priority: medium, feature

#437 Bug Fix
  discord/interactions.py
Labels: bug, priority: high

#464 Add fix for typing for ApplicationContext.author
  discord/commands/context.py
Labels: bug, priority: medium, status: awaiting review

#465 adds with_count to fetch_guild
  discord/client.py
  discord/guild.py
  discord/http.py
Labels: priority: low, status: awaiting review, feature

#427 add return type typing on discord.ui.*
  discord/ui/button.py
  discord/ui/item.py
  discord/ui/select.py
  discord/ui/view.py
Labels: documentation, priority: high, status: awaiting review

#456 Bugfix for task.loop
  discord/ext/tasks/__init__.py
Labels: bug, good first issue, priority: high, status: awaiting review

#471 add support for passing options in SlashCommand.__init__
  discord/commands/commands.py
Labels: priority: medium, status: awaiting review, feature

#474 Add aiohttp speedups to `speed`
  .gitignore
  setup.py
Labels: priority: medium, status: awaiting review

#488 New permission 1<<40
  discord/flags.py
  discord/permissions.py
Labels: documentation, priority: high, status: awaiting review, feature

#489 Update Activities with their real names
  discord/enums.py
  docs/api.rst
Labels: documentation, priority: medium, status: awaiting review

#476 Fix merge errors in utils.basic_autocomplete
  discord/utils.py
Labels: bug, documentation, priority: low, status: awaiting review

#504 Fix voice_client in ApplicationContext
  discord/commands/context.py
Labels: bug, priority: high, status: awaiting review

#496 Convert raw image URL into bytecode in `client.user.edit`
  discord/user.py
Labels: priority: low, status: awaiting review, feature

#503 Add autocomplete example
  examples/app_commands/slash_autocomplete.py
Labels: documentation, priority: medium, status: awaiting review

#92 Installing additional packages for aiohttp
  .gitignore
  README.rst
  docs/intro.rst
  docs/locale/ja/LC_MESSAGES/intro.po
Labels: status: awaiting review, dependencies, feature

#511 Hot Fix - CodeSpell
  docs/locale/ja/LC_MESSAGES/intro.po
Labels: priority: high

#510 Update button_roles.py
  examples/views/button_roles.py
Labels: documentation, priority: medium

#516 Fix type for User.accent_colour.
  discord/user.py
Labels: bug, documentation, priority: medium

#517 Fix make.bat Name
  docs/make.bat
Labels: documentation, priority: low

#521 Fix's Name Issues
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/locale/ja/LC_MESSAGES/api.po
  docs/locale/ja/LC_MESSAGES/ext/commands/api.po
  docs/locale/ja/LC_MESSAGES/ext/commands/index.po
  docs/locale/ja/LC_MESSAGES/ext/tasks/index.po
  docs/locale/ja/LC_MESSAGES/faq.po
  docs/locale/ja/LC_MESSAGES/index.po
  docs/locale/ja/LC_MESSAGES/intents.po
  docs/locale/ja/LC_MESSAGES/intro.po
  docs/locale/ja/LC_MESSAGES/logging.po
  docs/locale/ja/LC_MESSAGES/migrating.po
  docs/locale/ja/LC_MESSAGES/migrating_to_async.po
  docs/locale/ja/LC_MESSAGES/quickstart.po
Labels: documentation, priority: medium

#522 Fix WelcomeScreen typings
  discord/guild.py
  discord/http.py
  discord/welcome_screen.py
Labels: bug, priority: high
