Repository Pycord-Development/pycord, pull requests merged in 2021-12, with the labels that each got.

#533 Fix command name, option, and description validation
  discord/commands/commands.py
Labels: bug, priority: low, status: awaiting review

#540 Add support for slash-command groups on cogs
  discord/bot.py
  discord/cog.py
  discord/commands/commands.py
  discord/ext/commands/core.py
  examples/app_commands/slash_cog_groups.py
Labels: priority: high, status: in progress, feature

#537 Format
  .github/CONTRIBUTING.md
  discord/__main__.py
  discord/client.py
  discord/gateway.py
  examples/app_commands/slash_autocomplete.py
  examples/app_commands/slash_basic.py
  examples/app_commands/slash_cog.py
  examples/app_commands/slash_options.py
  examples/app_commands/slash_perms.py
  examples/background_task.py
  examples/background_task_asyncio.py
  examples/basic_bot.py
  examples/basic_voice.py
  examples/custom_context.py
  examples/edits.py
  examples/guessing_game.py
  examples/views/button_roles.py
  examples/views/confirm.py
  examples/views/counter.py
  examples/views/dropdown.py
  examples/views/ephemeral.py
  examples/views/link.py
  examples/views/persistent.py
  examples/views/tic_tac_toe.py
Labels: documentation, priority: medium

#507 ApplicationContext attributes
  discord/commands/context.py
Labels: priority: medium, status: in progress, feature

#551 Change if isinstance logic to elif
  discord/channel.py
Labels: priority: low, status: awaiting review

#470 Remove ids and grammar changes.
  examples/views/button_roles.py
Labels: documentation, priority: low, status: todo

#462 Redesigning slash command groups
  discord/bot.py
  discord/cog.py
  discord/commands/commands.py
  discord/ext/commands/core.py
  examples/app_commands/slash_cog_groups.py
Labels: priority: high, status: awaiting review, feature

#570 Use WeakValueDictionary for webhook locks.
  discord/webhook/async_.py
  discord/webhook/sync.py
Labels: bug, priority: high, status: awaiting review

#249 Format examples and add another example
  examples/app_commands/info.py
Labels: documentation

#428 Type hinting for discord.commands
  discord/asset.py
  discord/bot.py
  discord/commands/_types.py
  discord/commands/commands.py
  discord/commands/context.py
  discord/commands/errors.py
  discord/commands/permissions.py
  discord/ext/commands/bot.py
  discord/ext/commands/converter.py
  discord/ext/commands/help.py
  discord/ext/commands/view.py
  discord/flags.py
  discord/http.py
  discord/integrations.py
  discord/mentions.py
  discord/partial_emoji.py
  discord/types/interactions.py
  discord/utils.py
  discord/webhook/async_.py
  discord/webhook/sync.py
  discord/welcome_screen.py
Labels: documentation, priority: high, status: in progress

#441 baseholder implementation for timeouts
  discord/member.py
  discord/types/member.py
Labels: discord limitation, priority: medium, status: planned, feature

#583 Fix timeout permission
  discord/member.py
  discord/permissions.py
Labels: priority: high

#398 Fix for discord.User parsing
  discord/commands/commands.py
Labels: bug, priority: medium, status: awaiting review

#561 Add missing cast import from typing library
  discord/ext/tasks/__init__.py
Labels: bug, priority: medium, status: awaiting review

#484 Add More examples
  examples/interactionsBot/bot.py
  examples/interactionsBot/cog_group/__init__.py
  examples/interactionsBot/cogs/button_cog.py
  examples/interactionsBot/cogs/dropdown_cog.py
  examples/interactionsBot/cogs/slashGroup_cog.py
  examples/interactionsBot/cogs/slashOption_cog.py
  examples/interactionsBot/cogs/slash_cog.py
Labels: documentation, priority: low, status: awaiting review

#532 Voice Receiving
  .gitignore
  discord/__init__.py
  discord/errors.py
  discord/gateway.py
  discord/opus.py
  discord/sink.py
  discord/voice_client.py
  docs/api.rst
  examples/audio_recording.py
Labels: priority: medium, status: awaiting review, feature

#568 Document slash command groups
  .gitignore
  docs/application_commands.rst
Labels: documentation, priority: high, status: in progress

#547 Making A CODEOWNERS
  .github/CODEOWNERS
Labels: priority: medium

#619 Add a timeout_for method
  discord/member.py
Labels: priority: low, status: awaiting review, feature

#600 Add delay and delete_after Parameters on Interaction functions
  discord/interactions.py
  discord/message.py
  discord/utils.py
Labels: priority: medium, status: awaiting review, feature

#644 Fix guild avatars not working
  discord/member.py
Labels: bug, priority: high

#634 Global commands will be sent to Discord to register only if it differs from the existing global commands from Discord's servers
  discord/bot.py
Labels: good first issue, priority: medium, status: in progress

#645 Separate ApplicationContext.respond() and followup()
  discord/commands/context.py
Labels: priority: medium, status: awaiting review

#648 Fix converters
  discord/commands/commands.py
Labels: bug, priority: low, status: awaiting review

#652 Implement ApplicationContext.invoke
  discord/commands/commands.py
  discord/commands/context.py
Labels: priority: low, status: awaiting review, feature

#518 Add new `Thread.archive`
  discord/threads.py
Labels: priority: low, feature

#580 Fix to autocomplete's values (OptionChoices)
  discord/utils.py
Labels: bug, priority: high, status: awaiting review

#659 [bugfix] Move `ParamSpec` import into `if TYPE_CHECKING`
  discord/commands/commands.py
Labels: bug, priority: high, status: awaiting review

#631 Add permissions support to context menu commands
  discord/commands/commands.py
Labels: priority: high

#667 Type-hinted, un typehinted dunder methods
  discord/permissions.py
Labels: priority: medium

#647 Ability to reload application command callbacks
  discord/bot.py
Labels: priority: high, status: awaiting review, feature

#662 Rename Permission to CommandPermission
  discord/commands/commands.py
  discord/commands/permissions.py
  examples/app_commands/slash_cog_groups.py
  examples/app_commands/slash_perms.py
Labels: priority: low, status: awaiting review
