Repository Pycord-Development/pycord, pull requests merged in 2022-03, with the labels that each got.

#1090 Add `client` property to `Interaction` class
  discord/interactions.py
Labels: priority: medium, status: awaiting review, feature, Merge with squash

#1103 Add docs for `AutocompleteContext`, `Option`, `OptionChoice`, and `on_application_command*` events.
  discord/commands/context.py
  discord/commands/options.py
  discord/ui/input_text.py
  discord/ui/modal.py
  docs/api.rst
Labels: documentation, priority: high, status: awaiting review, bypass-review, Merge with squash

#1062 Add shortcut property to send modals via ApplicationContext
  discord/commands/context.py
  discord/interactions.py
  examples/modal_dialogs.py
Labels: priority: medium, status: awaiting review, feature, Merge with squash

#1053 Adds message_content intent to examples.
  examples/background_task.py
  examples/background_task_asyncio.py
  examples/basic_bot.py
  examples/basic_voice.py
  examples/converters.py
Labels: Merge with squash

#1088 Various Paginator fixes for `disable()`, `cancel()`, and `respond` methods.
  discord/ext/pages/pagination.py
Labels: priority: high, status: awaiting review, Merge with squash, pages

#1106 Add `custom_id` attribute to `PaginatorMenu` to fix bug with persistent views that include page groups
  discord/ext/pages/pagination.py
Labels: priority: high, bypass-review, Merge normally, pages

#1107 Fix attribute error with deprecated stage discovery
  discord/enums.py
  discord/stage_instance.py
Labels: bug

#1108 Fix scheduled event payload typings
  discord/types/scheduled_events.py
Labels: bug

#1105 Add scheduled_event attribute to stage instances
  discord/scheduled_events.py
  discord/stage_instance.py
  discord/types/channel.py
Labels: feature

#1112 Update `HTTPClient.kick()` to use `reason` kwarg
  discord/http.py
Labels: bug, priority: high, status: awaiting review, Merge normally

#1116 Fix for PartialMessageable TypeError in ext.pages
  discord/ext/pages/pagination.py
Labels: priority: high, bypass-review, Merge normally, pages

#1121 Add `CommandPermission` docs
  docs/api.rst
Labels: documentation, priority: high, bypass-review

#1123 Add `Page` class to `ext.pages` to allow for greater flexibility with page contents
  discord/ext/pages/pagination.py
  docs/ext/pages/index.rst
  examples/views/paginator.py
Labels: priority: high, bypass-review, Merge with squash, pages

#1127 Fix some keyword arguments failing
  discord/commands/core.py
Labels: bug

#1132 Add missing **kwargs param to support non-explicit parameters in `SlashCommandGroup` (fixes issue introduced by #1127)
  discord/commands/core.py
Labels: bug, priority: high, bypass-review, Merge normally

#1135 Small change to the DropDown example
  examples/views/dropdown.py
Labels: documentation, priority: low, status: in progress, Merge with squash

#1139 Remove outdated note
  docs/faq.rst
Labels: documentation

#1138 Fix `slash_autocomplete` example
  examples/app_commands/slash_autocomplete.py
Labels: priority: high, status: awaiting review, examples

#1027 Run parent checks in `can_run`
  discord/commands/core.py
Labels: priority: medium, status: awaiting review, Merge with squash

#1146 Improved Readme Badges
  README.rst
Labels: documentation, priority: low, status: awaiting review, Merge with squash

#1151 Add missing `**kwargs` to SlashCommandGroup
  discord/commands/core.py
Labels: bug, priority: medium, status: awaiting review, Merge with squash

#1161 Add docs for `InputTextStyle` enum values.
  docs/api.rst
Labels: documentation, priority: high, bypass-review, Merge with squash

#1164 Add `menu_placeholder` parameter to allow specifying placeholder text for the PageGroup menu
  discord/ext/pages/pagination.py
Labels: priority: medium, status: awaiting review, feature, Merge with squash, pages

#1160 Fix cog slash commands when using ctx.invoke()
  discord/cog.py
  discord/commands/core.py
Labels: bug, priority: high, status: awaiting review, Merge with squash

#1157 Fix typehints for `send_modal` methods
  discord/commands/context.py
Labels: bug, priority: low, status: awaiting review

#1174 Add datetime task to examples
  examples/background_task.py
Labels: priority: medium, status: awaiting review, Merge with squash, examples

#1167 Add `Modal.on_error`
  discord/ui/modal.py
Labels: priority: low, status: awaiting review, feature, Merge with squash

#1141 Add `Client.get_message`
  discord/client.py
  discord/flags.py
  docs/faq.rst
Labels: priority: medium, status: awaiting review, feature, Merge with squash

#1170 fix some kwargs failing
  .gitignore
  discord/commands/core.py
Labels: bug

#1129 Implement application command permissions v2
  discord/commands/core.py
  discord/commands/permissions.py
  docs/api.rst
Labels: discord limitation, status: in progress, Merge with squash, documentation needed

#1101 Add `Guild._fetch_role()` private method to support proper handling of role mentionable in slash command options
  discord/commands/core.py
  discord/guild.py
  discord/utils.py
Labels: bug, priority: high, status: awaiting review, Merge with squash

#1186 Fix reloading application command callbacks
  discord/commands/core.py
Labels: bug, priority: medium, status: awaiting review

#1188 Allow type checkers to treat cached_property as a normal property.
  discord/commands/context.py
  discord/utils.py
Labels: Merge with squash

#1203 Add url property to scheduled events
  discord/scheduled_events.py
Labels: bug, feature
