Repository Pycord-Development/pycord, pull requests merged in 2022-01, with the labels that each got.

#613 Add timeout example
  examples/timeout.py
Labels: priority: medium, status: awaiting review, Merge with squash

#509 Add description to Attachments and Files
  discord/file.py
  discord/http.py
  discord/interactions.py
  discord/message.py
  discord/webhook/async_.py
Labels: priority: medium, status: awaiting review, feature

#674 Cooldowns and max concurrency for application commands
  discord/commands/commands.py
  discord/ext/commands/core.py
Labels: priority: low, status: awaiting review, feature, Merge with squash

#211 Add support for `guild scheduled events`
  discord/__init__.py
  discord/abc.py
  discord/audit_logs.py
  discord/client.py
  discord/commands/errors.py
  discord/enums.py
  discord/errors.py
  discord/flags.py
  discord/guild.py
  discord/http.py
  discord/invite.py
  discord/iterators.py
  discord/raw_models.py
  discord/scheduled_events.py
  discord/state.py
  discord/types/audit_log.py
  discord/types/guild.py
  discord/types/invite.py
  discord/types/raw_models.py
  discord/types/scheduled_events.py
  docs/api.rst
Labels: priority: high, status: awaiting review, feature, Merge with squash

#671 Treating None embeds and views as not having embeds and views in send_message
  discord/interactions.py
Labels: feature request, priority: low, status: awaiting review

#701 Fix `ApplicationCommand.__eq__`
  discord/commands/commands.py
Labels: bug, priority: high, status: awaiting review

#705 Fixes #704
  discord/bot.py
Labels: bug, priority: high, Merge normally

#709 Document Missing Raw Payload
  docs/api.rst
Labels: documentation, priority: medium, status: awaiting review, Merge normally

#718 Fix Max Concurrency On Application Commands
  discord/commands/commands.py
Labels: bug, priority: medium, status: awaiting review, Merge normally

#724 Fix #716 and #718
  discord/commands/commands.py
Labels: bug, priority: medium, status: awaiting review, Merge normally

#629 ext.pages updates/changes
  discord/ext/pages/pagination.py
  docs/ext/pages/index.rst
  examples/views/paginator.py
Labels: documentation, priority: high, status: awaiting review, feature, Merge with rebase

#677 Add a cooldown example
  examples/cooldown.py
Labels: documentation, priority: low, Merge with squash

#673 discord: client: Ignore RuntimeError when calling add_signal_handler()
  discord/client.py
Labels: bug, priority: medium, Merge with squash

#679 `OptionChoice` Bug Fix
  discord/commands/commands.py
Labels: bug, priority: medium, Merge with squash

#697 Add Walk (application) Commands on `SlashCommandGroup` and `discord.Bot`
  discord/bot.py
  discord/commands/commands.py
Labels: priority: medium, feature, Merge with squash

#725 Fix ScheduledEventLocation documentation
  discord/scheduled_events.py
  docs/api.rst
Labels: documentation

#733 Fix attribute error for ScheduledEventLocation
  discord/audit_logs.py
  discord/guild.py
  discord/scheduled_events.py
Labels: bug, priority: high, Merge normally

#736 Update StackOverflow tag in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation, priority: low, status: awaiting review, Merge with rebase

#752 Merge about.md with README.md
  README.rst
  about.md
Labels: documentation, priority: medium, Merge with squash

#729 Fixed error with options defined in kwargs (#555)
  discord/commands/commands.py
Labels: bug, priority: medium, status: awaiting review, Merge with squash

#766 Rename commands.py to core.py in discord.commands
  discord/cog.py
  discord/commands/__init__.py
  discord/commands/context.py
  discord/commands/core.py
  examples/views/button_roles.py
Labels: priority: high, status: awaiting review, Merge normally

#777 Typing and importing fixes
  discord/cog.py
  discord/commands/core.py
  discord/ext/commands/cog.py
  discord/ext/pages/pagination.py
  discord/flags.py
  discord/http.py
  discord/integrations.py
  discord/interactions.py
  discord/message.py
  discord/role.py
  discord/state.py
  discord/template.py
  discord/widget.py
Labels: priority: high, status: awaiting review, Merge normally

#767 Move options to discord/commands/options.py
  discord/commands/__init__.py
  discord/commands/core.py
  discord/commands/options.py
Labels: priority: medium, status: awaiting review, Merge normally

#764 Add invitable attribute to AuditLogDiff
  docs/api.rst
Labels: priority: medium, status: awaiting review, feature, Merge with squash

#784 fix: typo in `remove_user`
  discord/threads.py
Labels: priority: low, status: awaiting review, Merge normally

#796 fix: typo in `MessageFlags.loading`
  discord/flags.py
Labels: priority: low, status: awaiting review, Merge normally

#806 chore: bump sphinx to `4.4.0`
  setup.py
Labels: priority: low, status: awaiting review, Merge normally

#712 Implemented attachments in Webhook.edit_message and WebhookMessage.edit
  discord/interactions.py
  discord/webhook/async_.py
Labels: priority: medium, feature, Merge with squash

#807 Note Feature Freeze
  .github/PULL_REQUEST_TEMPLATE.md
Labels: priority: high, status: awaiting review, Merge with squash

#802 [ext.pages] Add ability to specify in which row the paginator buttons are displayed
  discord/ext/pages/pagination.py
Labels: priority: low, Merge with squash, pages

#785 [ext.pages] Add example for using emojis for buttons instead of labels
  docs/ext/pages/index.rst
  examples/views/paginator.py
Labels: priority: low, status: awaiting review, Merge normally, examples, pages

#745 Fix for setting Embed object properties to `None` upon creation
  discord/embeds.py
Labels: priority: medium

#711 Fix `discord.utils.escape_markdown` only escaping first link on line
  discord/utils.py
Labels: bug, priority: medium, Merge normally

#809 Fix ScheduledEvent (gateway) events not working
  discord/state.py
Labels: bug, priority: high

#815 Make channel_id default to the current channel
  discord/ext/commands/converter.py
Labels: bug, priority: low, status: awaiting review, Merge normally

#821 Implement MessageInteraction class
  discord/interactions.py
  discord/message.py
  discord/types/interactions.py
Labels: status: planned

#822 [ext.commands] Fix non-async method in owner_or_permission doc example
  discord/ext/commands/core.py
Labels: priority: low

#823 Fix documentation table of contents
  docs/ext/pages/index.rst
Labels: documentation

#817 Extension fixes
  discord/bot.py
  discord/ext/commands/core.py
Labels: bug

#689 remove useless lambda functions
  discord/client.py
Labels: priority: medium, feature, Merge with squash

#810 Fix behaviour of ScheduledEvent subs iterator
  discord/http.py
  discord/iterators.py
  discord/scheduled_events.py
Labels: bug

#795 Fix `Permissions.all()`
  discord/permissions.py
Labels: priority: high, status: awaiting review, Merge with squash

#829 Revert #817 due to high-severity prefix command errors introduced by its changes
  discord/bot.py
  discord/ext/commands/core.py
Labels: bug, priority: high, Merge normally

#828 Add back missing PartialMessageable import
  discord/interactions.py
Labels: bug

#832 Refactor Voice Recording
  .gitignore
  discord/__init__.py
  discord/errors.py
  discord/opus.py
  discord/sinks/__init__.py
  discord/sinks/core.py
  discord/sinks/errors.py
  discord/sinks/m4a.py
  discord/sinks/mka.py
  discord/sinks/mkv.py
  discord/sinks/mp3.py
  discord/sinks/mp4.py
  discord/sinks/ogg.py
  discord/sinks/pcm.py
  discord/sinks/wave.py
  discord/voice_client.py
  docs/api.rst
  examples/audio_recording.py
Labels: bypass-review

#449 Document application commands
  .gitignore
  README.rst
  discord/commands/core.py
  docs/api.rst
  docs/application_commands.rst
  docs/guide/starting-out/making-a-bot.md
  setup.py
Labels: documentation, priority: high, status: in progress, Merge normally

#789 Bugfix/modify mypy ci
  .github/workflows/mypy.yml
  discord/commands/core.py
  mypy.ini
Labels: priority: low, status: awaiting review, Merge with squash

#834 refactor: undo guide
  docs/discord.rst
  docs/guide/ext/commands/checks.md
  docs/guide/ext/commands/cogs.md
  docs/guide/ext/commands/index.md
  docs/guide/ext/pages/index.md
  docs/guide/ext/tasks/index.md
  docs/guide/index.md
  docs/guide/interactions/button_views.md
  docs/guide/interactions/context_menus.md
  docs/guide/interactions/select_views.md
  docs/guide/interactions/slash_commands.md
  docs/guide/misc/webhooks.md
  docs/guide/starting-out/initial-files.md
  docs/images/guide/message_command.png
  docs/images/guide/user_command.png
  docs/index.rst
  docs/installing.rst
  docs/intents.rst
  docs/logging.rst
  examples/app_commands/info.py
  examples/app_commands/slash_cog.py
  examples/app_commands/slash_cog_groups.py
  examples/cooldown.py
  examples/interactionsBot/bot.py
  examples/interactionsBot/cogs/button_cog.py
  examples/interactionsBot/cogs/dropdown_cog.py
  examples/interactionsBot/cogs/slashOption_cog.py
  examples/interactionsBot/cogs/slash_cog.py
  examples/views/button_roles.py
  examples/views/paginator.py
Labels: bypass-review

#836 fix: options being in the wrong place
  discord/commands/core.py
Labels: bypass-review

#681 Fix: Fix discord.errors not working
  discord/__init__.py
Labels: bug, priority: high, status: awaiting review, Merge normally

#791 Improve examples
  examples/app_commands/slash_options.py
  examples/custom_context.py
Labels: priority: low, status: awaiting review, Merge normally, examples

#762 chore: bump version to `2.0.0-rc.1`
  discord/__init__.py
Labels: priority: high, status: awaiting review, Merge with rebase

#853 Fix converters using message.mentions
  discord/ext/commands/converter.py
Labels: bug

#849 Add docs for `MessageInteraction` class
  docs/api.rst
Labels: documentation, priority: low, status: awaiting review, Merge normally

#859 [ext-pages] Fix for specifying an initial page before sending the paginator
  discord/ext/pages/pagination.py
Labels: feature request, Merge with squash, pages

#432 Merge core/typing
  .github/workflows/docs.yml
  discord/asset.py
  discord/bot.py
  discord/commands/_types.py
  discord/commands/context.py
  discord/commands/core.py
  discord/commands/errors.py
  discord/commands/permissions.py
  discord/ext/commands/bot.py
  discord/ext/commands/converter.py
  discord/ext/commands/help.py
  discord/ext/commands/view.py
  discord/flags.py
  discord/http.py
  discord/integrations.py
  discord/mentions.py
  discord/partial_emoji.py
  discord/types/interactions.py
  discord/ui/button.py
  discord/ui/item.py
  discord/ui/select.py
  discord/ui/view.py
  discord/utils.py
  discord/webhook/async_.py
  discord/webhook/sync.py
  discord/welcome_screen.py
  requirements.txt
Labels: priority: high, status: in progress, status: planned, Merge with squash

#864 Revert "Merge core/typing (#432)"
  .github/workflows/docs.yml
  discord/asset.py
  discord/bot.py
  discord/commands/_types.py
  discord/commands/context.py
  discord/commands/core.py
  discord/commands/errors.py
  discord/commands/permissions.py
  discord/ext/commands/bot.py
  discord/ext/commands/converter.py
  discord/ext/commands/help.py
  discord/ext/commands/view.py
  discord/flags.py
  discord/http.py
  discord/integrations.py
  discord/mentions.py
  discord/partial_emoji.py
  discord/types/interactions.py
  discord/ui/button.py
  discord/ui/item.py
  discord/ui/select.py
  discord/ui/view.py
  discord/utils.py
  discord/webhook/async_.py
  discord/webhook/sync.py
  discord/welcome_screen.py
  requirements.txt
Labels: priority: high

#868 Bump version to 2.0.0 beta
  discord/__init__.py
  setup.py
Labels: priority: high, status: awaiting review, Merge normally

#846 Fix error with option default params
  discord/commands/core.py
Labels: bug, priority: medium, status: awaiting review, Merge normally

#876 Fix role `icon` argument not setting unicode_emoji to None
  discord/role.py
Labels: bug, priority: medium, status: awaiting review, Merge with squash

#848 fix: do some typing in commands/context.py
  discord/commands/context.py
Labels: priority: low, status: awaiting review, Merge normally

#838 Fix extensions in discord.Bot
  discord/bot.py
  discord/cog.py
  discord/commands/core.py
  discord/ext/commands/core.py
Labels: bug, priority: high, status: awaiting review, Merge normally

#880 Add missing `guild_ids` parameter to `SlashCommandGroup.create_subgroup`
  discord/commands/core.py
Labels: priority: medium, status: awaiting review

#877 Add missing docs
  discord/enums.py
  docs/api.rst
  docs/cogs.rst
Labels: documentation, priority: high, status: in progress, Merge with squash

#892 Remove MISSING check from embed, embeds, view (fix for #303)
  discord/interactions.py
Labels: bug
