Repository Pycord-Development/pycord, pull requests merged in 2022-04, with the labels that each got.

#1193 Documentation Updates
  discord/__init__.py
  discord/bot.py
  discord/client.py
  discord/cog.py
  discord/commands/core.py
  discord/commands/permissions.py
  discord/errors.py
  discord/member.py
  discord/scheduled_events.py
  discord/sinks/core.py
  discord/sinks/errors.py
  discord/sinks/m4a.py
  discord/sinks/mka.py
  discord/sinks/mkv.py
  discord/sinks/mp3.py
  discord/sinks/mp4.py
  discord/sinks/ogg.py
  discord/sinks/pcm.py
  discord/sinks/wave.py
  discord/ui/input_text.py
  discord/ui/modal.py
  discord/utils.py
  discord/voice_client.py
  discord/webhook/async_.py
  docs/api.rst
  docs/cogs.rst
  docs/conf.py
  docs/ext/commands/api.rst
  docs/ext/commands/commands.rst
  docs/index.rst
  docs/installing.rst
  docs/migrating_to_v1.rst
  docs/quickstart.rst
  docs/whats_new.rst
Labels: documentation, status: awaiting review, Merge with squash

#1217 Ban pagination
  discord/guild.py
  discord/http.py
  discord/iterators.py
Labels: priority: high, status: awaiting review, Merge with squash

#1221 Fix race condition in autocomplete
  discord/bot.py
Labels: priority: medium, status: awaiting review, Merge with squash

#1067 [WIP] Add `reason` kwarg for message deletion (for audit log support)
  discord/channel.py
  discord/http.py
  discord/message.py
Labels: priority: high, status: awaiting review, Merge with squash

#1224 [ext.pages] Fix for "Unknown Message" errors when using ephemeral paginators
  discord/ext/pages/pagination.py
Labels: bug, priority: high, status: awaiting review, Merge with squash, pages

#1228 Remove deprecated mention syntax
  discord/member.py
Labels: priority: low, status: awaiting review, Merge with squash

#986 Make `get_desynced_commands` work with slash command groups
  discord/bot.py
  discord/commands/core.py
Labels: priority: medium, status: in progress, Merge with squash

#1229 Fix option parsing
  discord/commands/core.py
Labels: priority: high, status: in progress, Merge with squash

#1211 Add notification to stage instance creation
  discord/channel.py
  discord/http.py
Labels: feature

#1208 Command registration rewrite v4
  discord/bot.py
  discord/commands/core.py
  discord/commands/options.py
Labels: priority: high, status: awaiting review

#1227 [ext.pages] General fixes and enhancements
  discord/ext/pages/pagination.py
Labels: bug, priority: high, status: awaiting review, feature, Merge with squash, pages

#1232 Localization Fixes
  discord/commands/core.py
  discord/http.py
  discord/types/interactions.py
Labels: bug, status: awaiting review, feature

#1231 Text in voice
  discord/abc.py
  discord/channel.py
  discord/message.py
  discord/state.py
  discord/threads.py
Labels: priority: medium, status: awaiting review, Merge with squash

#1202 Ability to set guild_ids for all commands in a cog
  discord/cog.py
Labels: status: awaiting review, feature, Merge with squash

#1235 Update bot.py
  discord/bot.py
Labels: bug, priority: high, Merge with squash

#1237 [ext.pages] Fix logic for `page_count` calculation
  discord/ext/pages/pagination.py
Labels: bug, priority: high, bypass-review, Merge normally, pages

#1238 Fix embeds not getting edited in with partial messages
  discord/abc.py
  discord/message.py
Labels: bug

#1131 discord.ext.bridge
  discord/bot.py
  discord/cog.py
  discord/enums.py
  discord/ext/bridge/__init__.py
  discord/ext/bridge/bot.py
  discord/ext/bridge/context.py
  discord/ext/bridge/core.py
  discord/utils.py
  docs/conf.py
  docs/ext/bridge/index.rst
  docs/index.rst
  examples/bridge_commands.py
  setup.py
Labels: priority: medium, status: awaiting review, feature, Merge with squash

#1240 Fix py3.10 UnionType checks
  discord/enums.py
Labels: bug, priority: high, status: awaiting review, Merge with squash

#1253 Add reason to delete_messages, fixes #1252
  discord/threads.py
Labels: priority: high, status: awaiting review

#1254 Add `jump_url` property to channels
  discord/abc.py
  discord/channel.py
Labels: status: awaiting review, feature

#1257 Slash Command Channel Parsing Bug Fixes
  discord/channel.py
  discord/commands/core.py
Labels: priority: high, status: awaiting review, Merge with squash

#1261 Hotfix for spelling errors, minor indentation errors, update values to double quoted strings
  discord/channel.py
Labels: bypass-review

#1258 [ext.pages] Add `Paginator.edit()` method
  discord/ext/pages/pagination.py
Labels: priority: medium, status: awaiting review, feature, Merge with squash, ext.pages

#1264 chore: run linting operations
  discord/abc.py
  discord/bot.py
  discord/cog.py
  discord/commands/core.py
  discord/commands/options.py
  discord/enums.py
  discord/ext/bridge/__init__.py
  discord/ext/bridge/core.py
  discord/guild.py
  discord/http.py
  discord/iterators.py
  discord/message.py
  discord/sinks/core.py
  discord/sinks/m4a.py
  discord/sinks/mka.py
  discord/sinks/mkv.py
  discord/sinks/mp3.py
  discord/sinks/mp4.py
  discord/sinks/ogg.py
  discord/sinks/wave.py
  discord/state.py
  discord/threads.py
  discord/ui/modal.py
  discord/utils.py
  discord/voice_client.py
  discord/webhook/async_.py
  examples/background_task.py
  examples/background_task_asyncio.py
  examples/basic_voice.py
  examples/bridge_commands.py
  examples/views/dropdown.py
Labels: bypass-review

#1267 [ext.pages] Hotfix to make PaginatorMenu use interaction routes for updates
  discord/ext/pages/pagination.py
Labels: bug, bypass-review, ext.pages

#1268 Fix PartialMessage.edit
  discord/message.py
Labels: bug

#1270 [ext.pages] Hotfix to remove custom_id parameter from being passed to default PaginatorMenu
  discord/ext/pages/pagination.py
Labels: bug, priority: high, bypass-review, Merge with squash, ext.pages

#1272 [ext.pages] Hotfix to fully fix #1269
  discord/ext/pages/pagination.py
Labels: bug, priority: high, bypass-review, ext.pages

#1181 Add `EmbedField` object to allow for easier embed class instance creation
  discord/embeds.py
  docs/api.rst
Labels: priority: low, status: awaiting review, feature, Merge with squash

#1271 Add validation of option names and descriptions
  discord/commands/core.py
Labels: feature, Merge with squash

#1065 Add library-level enforcement of component field limits
  discord/components.py
  discord/ui/button.py
  discord/ui/input_text.py
  discord/ui/modal.py
  discord/ui/select.py
Labels: priority: medium, status: awaiting review, Merge with squash

#1250 [bridge] Fix conversion exception
  discord/ext/bridge/core.py
Labels: priority: medium, status: awaiting review, Merge with squash

#1000 Support providing option channel types as list
  discord/commands/options.py
Labels: bug, priority: high, status: in progress, Merge with squash

#1285 on_thread_create event
  discord/state.py
  docs/api.rst
Labels: priority: high, feature

#1286 Context.me returning ClientUser when guilds intent is absent
  discord/ext/commands/context.py
Labels: priority: low, status: awaiting review, feature, Merge with squash

#1289 Add additional logic for optional component property setters to avoid TypeErrors
  discord/ui/button.py
  discord/ui/input_text.py
  discord/ui/select.py
Labels: bug, priority: high, bypass-review, Merge with squash

#1288 [ext.pages] Compatibility patch for ext.bridge
  discord/ext/pages/pagination.py
Labels: priority: high, status: awaiting review, Merge with squash

#1287 Change Embed.fields to always return a list
  discord/embeds.py
Labels: bug

#1295 [ext.pages] Fix import for BridgeContext
  discord/ext/pages/pagination.py
Labels: bug, priority: high, bypass-review, Merge with squash, ext.pages

#1301 Hotfix to add debug warning to catch deprecated perms v1 usage until v2 perms are implemented
  discord/bot.py
Labels: bug, priority: high, bypass-review, Merge with squash

#1299 Update `Message.edit` type hinting overload and remove resulting redundant overloads
  discord/message.py
Labels: priority: high, status: awaiting review, Merge with squash

#1300 [ext.pages] Add `files` parameter to `Page` object
  discord/ext/pages/pagination.py
Labels: feature request, priority: low, status: awaiting review, feature, Merge with squash, ext.pages

#1199 Add `disable_all_items` in `View`
  discord/ui/view.py
Labels: status: awaiting review, feature
