Repository Pycord-Development/pycord, pull requests merged in 2022-10, with the labels that each got.

#1657 Upgrade utils.deprecated & add utils.warn_deprecated
  discord/utils.py
Labels: status: awaiting review, feature

#1557 New delete_message_seconds parameter
  discord/guild.py
  discord/http.py
Labels: status: awaiting review, feature

#1659 Add View.get_item shortcut method
  discord/ui/view.py
Labels: status: awaiting review, feature

#1642 [ext.bridge] Permission decorators and invoke function
  CHANGELOG.md
  discord/cog.py
  discord/commands/permissions.py
  discord/ext/bridge/context.py
  discord/ext/bridge/core.py
  discord/ext/commands/core.py
  docs/ext/bridge/api.rst
Labels: feature, ext.bridge

#1658 Add raw_mention utils
  CHANGELOG.md
  discord/utils.py
Labels: status: in progress, feature

#1609 Rename `original_message` to `original_response`
  CHANGELOG.md
  discord/commands/context.py
  discord/ext/pages/pagination.py
  discord/interactions.py
Labels: status: in progress

#1663 Fix changelog for #1609
  CHANGELOG.md
Labels: priority: low, status: awaiting review

#1669 Remove dapi server from links
  README.rst
Labels: documentation, status: awaiting review

#1675 fix: README.rst grammar
  README.rst
Labels: hacktoberfest-accepted

#1676 Add brief Attribute to BridgeSlashCommand
  discord/ext/bridge/core.py
Labels: hacktoberfest-accepted

#1668 Pep 517
  .github/workflows/docs.yml
  .isort.cfg
  .pylintrc
  MANIFEST.in
  discord/__init__.py
  discord/_version.py
  docs/conf.py
  mypy.ini
  pyproject.toml
  pytest.ini
  setup.py
Labels: priority: medium, status: in progress

#1680 Fix errors that will occur in python3.11
  discord/ext/commands/flags.py
  discord/utils.py
Labels: bug, priority: medium

#1695 Fix bridge.has_permissions
  discord/ext/bridge/core.py
Labels: bug, priority: medium

#1689 feat(docs): warning on overriding on_connect
  discord/bot.py
  docs/api.rst
Labels: documentation, priority: low

#1678 Reworked `get_application_command` behaviour
  discord/bot.py
Labels: bug, priority: medium, feature

#1699 Add Docstring to Enum for Option descriptions, issue 1510
  discord/commands/options.py
  discord/enums.py
  docs/api.rst
Labels: priority: low, status: awaiting review

#1697 Doc restyle
  .github/workflows/docs.yml
  discord/ext/commands/help.py
  discord/object.py
  docs/_static/codeblocks.css
  docs/_static/copy.js
  docs/_static/css/custom.css
  docs/_static/custom.js
  docs/_static/icons.css
  docs/_static/icons.woff
  docs/_static/js/custom.js
  docs/_static/scorer.js
  docs/_static/settings.js
  docs/_static/sidebar.js
  docs/_static/style.css
  docs/_templates/genindex.html
  docs/_templates/layout.html
  docs/_templates/relations.html
  docs/conf.py
  docs/images/snake_dark.svg
  docs/whats_new.rst
  pyproject.toml
Labels: documentation, priority: medium, status: in progress

#1719 fix: #1674
  discord/abc.py
Labels: bug

#1723 Fix message send flags
  discord/abc.py
Labels: bug, priority: high, status: awaiting review

#1726 Pin cchardet version and add qualifiers
  pyproject.toml
Labels: priority: low, status: awaiting review, dependencies
