Repository Pycord-Development/pycord, pull requests merged in 2022-05, with the labels that each got.

#1303 [Perms v2] Additional implementations
  discord/audit_logs.py
  discord/bot.py
  discord/enums.py
  discord/http.py
  discord/state.py
  discord/types/interactions.py
Labels: priority: high, status: awaiting review, feature

#1319 Add `View.enable_all_items`
  discord/ui/view.py
Labels: status: awaiting review, feature

#1317 Add is_nsfw to voice channels
  discord/channel.py
Labels: status: awaiting review, feature

#1326 Perms v2 Audit Log Documentation
  docs/api.rst
Labels: documentation, status: awaiting review

#1251 Rewrite options
  discord/commands/core.py
  discord/commands/options.py
  discord/enums.py
Labels: bug, priority: high, status: in progress, feature, Merge with squash

#1328 Permissions v2 - Redo for merge conflicts
  discord/audit_logs.py
  discord/bot.py
  discord/commands/core.py
  discord/commands/permissions.py
  discord/enums.py
  discord/http.py
  discord/state.py
  discord/types/interactions.py
  docs/api.rst
Labels: priority: high, bypass-review, feature, Merge with squash

#1292 Enum options
  discord/commands/core.py
  discord/commands/options.py
Labels: status: awaiting review, feature, Merge with squash

#1311 Change `Modal.children` to be a property, allow instantiating with list of InputText components
  discord/ui/modal.py
Labels: priority: medium, status: awaiting review, feature, Merge with squash

#1335 Update slash command permissions example
  examples/app_commands/slash_perms.py
Labels: priority: medium, status: awaiting review

#1339 Fix parsing for string, integer, number, and boolean option types
  discord/commands/core.py
Labels: bug

#1340 Add `file` and `files` parameters to `InteractionResponse.edit_message()`
  discord/interactions.py
Labels: status: awaiting review, feature

#1249 Forum channels support
  discord/abc.py
  discord/channel.py
  discord/flags.py
  discord/guild.py
  discord/http.py
  discord/threads.py
  discord/types/channel.py
Labels: priority: high, status: in progress, feature, Merge with squash, documentation needed, upcoming discord feature

#1274 Implement Interaction.to_dict
  discord/interactions.py
Labels: priority: medium, status: awaiting review, feature

#1350 [ext.pages] Fixes and enhancements for `PageGroup` handling
  discord/ext/pages/pagination.py
Labels: bug, priority: high, bypass-review, feature, Merge with squash, ext.pages

#1357 Fix RuntimeError
  discord/interactions.py
Labels: bug, priority: high, bypass-review

#1355 Support event covers for audit logs
  discord/audit_logs.py
Labels: feature

#1359 Fix enum options breaking with redesigned options
  discord/commands/core.py
Labels: bug

#1363 Fix the enum options fix breaking bridge commands
  discord/commands/core.py
Labels: bug

#1368 Change guild_only to dm_permission in to_dict
  discord/commands/core.py
Labels: bug, priority: high

#1369 Fix #1364
  discord/scheduled_events.py
Labels: bug

#1370 Add news attribute to TextChannel
  discord/channel.py
Labels: bug

#1386 Fix #1385
  discord/commands/core.py
Labels: bug, priority: high, status: awaiting review, Merge with rebase

#1391 Fix `self._application_commands.pop` in `remove_application_command`
  discord/bot.py
Labels: bug, priority: high, status: awaiting review, Merge with squash
