Repository Pycord-Development/pycord, pull requests merged in 2022-07, with the labels that each got.

#1460 Implement app_permissions and fix stuff
  discord/commands/context.py
  discord/ext/commands/converter.py
  discord/ext/commands/core.py
  discord/interactions.py
  discord/types/interactions.py
  docs/conf.py
  docs/faq.rst
Labels: bug, documentation, priority: high, status: awaiting review, feature, Merge with squash, upcoming discord feature

#1452 Update ApplicationContext Documentation
  discord/commands/context.py
Labels: documentation

#1464 Update thread.members on thread.fetch_members
  discord/threads.py
Labels: bug, priority: high, status: awaiting review, Merge with rebase

#1465 Example of using semi-implemented private emojis.
  examples/create_private_emoji.py
Labels: documentation

#1456 Update the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: priority: low, status: awaiting review, Merge with squash

#1316 Implement Automod Features
  discord/automod.py
  discord/enums.py
  discord/flags.py
  discord/guild.py
  discord/http.py
  discord/raw_models.py
  discord/state.py
  discord/types/audit_log.py
  discord/types/automod.py
  discord/types/embed.py
  discord/types/guild.py
  discord/types/message.py
  discord/types/raw_models.py
  docs/api.rst
Labels: priority: high, status: awaiting review, feature, Merge with squash, upcoming discord feature

#1463 Add minmax length
  discord/commands/options.py
Labels: priority: medium, status: in progress, feature, Merge with squash

#1360 Fix AttributeError: 'NoneType' object has no attribute 'encode'
  discord/voice_client.py
Labels: priority: high, status: awaiting review, Merge with rebase

#1486 feat: add additional operations to `BaseFlags`
  discord/flags.py
  discord/permissions.py
Labels: status: awaiting review, feature, Merge with squash

#1473 Fix type issues in options.py
  discord/commands/options.py
Labels: priority: high, status: awaiting review, Merge with squash, documentation needed

#1488 2.0 Migration Guide + Changelog re-write
  docs/application_commands.rst
  docs/index.rst
  docs/installing.rst
  docs/migrating_to_v2.rst
  docs/whats_new.rst
Labels: documentation, help wanted, priority: high, status: in progress, Merge with squash

#1492 Add interaction support for View.message and add disable_on_timeout to Views
  discord/interactions.py
  discord/ui/view.py
Labels: priority: medium, status: awaiting review, feature, Merge with squash

#1521 Update content retrieval from AutoModActionExecution
  discord/raw_models.py
Labels: bug, priority: high, status: awaiting review, Merge with rebase

#1504 Docs rewrite
  discord/__init__.py
  discord/appinfo.py
  discord/bot.py
  discord/client.py
  discord/cog.py
  discord/commands/context.py
  discord/commands/core.py
  discord/commands/options.py
  discord/gateway.py
  discord/guild.py
  discord/member.py
  discord/object.py
  discord/raw_models.py
  discord/scheduled_events.py
  discord/team.py
  docs/api.rst
Labels: bug, documentation

#1535 Implement app_commands_badge in flags.py
  discord/flags.py
Labels: feature

#1536 Adding RPC endpoint support (Client.fetch_application)
  discord/client.py
  discord/http.py
Labels: feature, undocumented discord feature
