Repository Pycord-Development/pycord, pull requests merged in 2022-08, with the labels that each got.

#1541 Fix Enum options breaking again & wrong typing import
  discord/commands/options.py
  discord/shard.py
Labels: bug

#1530 Adjust category and guild _channels attributes to work with NoneType positions
  discord/channel.py
  discord/guild.py
Labels: bug

#1550 Make `SelectOption.emoji` a property
  discord/components.py
Labels: bug, feature

#799 Adding `on_check_failure` to `View` class
  discord/ui/view.py
Labels: priority: low, status: planned, feature, Merge normally

#1546 Improve sticker creation checks
  discord/guild.py
Labels: bug, priority: high, Merge with squash

#1551 Fix threads made from messages breaking
  discord/message.py
  discord/state.py
Labels: bug

#1522 Add overloads to load_extension(s)
  discord/cog.py
Labels: priority: low, status: awaiting review

#1553 Correct location of app_commands_badge flag
  discord/flags.py
Labels: feature, Merge with squash

#1559 Implement `resume_gateway_url`
  discord/gateway.py
  discord/shard.py
Labels: priority: high, status: awaiting review, feature, Merge with squash, upcoming discord feature

#1563 Avoid unnecessary call to `sync_commands`
  discord/bot.py
Labels: bug, priority: medium, status: awaiting review, Merge with squash

#1496 ext.bridge improvements
  discord/commands/core.py
  discord/ext/bridge/bot.py
  discord/ext/bridge/context.py
  discord/ext/bridge/core.py
  discord/interactions.py
  discord/utils.py
  docs/api.rst
  docs/ext/bridge/api.rst
  examples/bridge_commands.py
Labels: status: awaiting review, feature, Merge with squash, ext.bridge

#1589 Fix required parameters validation error
  discord/bot.py
  discord/cog.py
  discord/commands/core.py
Labels: bug

#1594 Fix subcommands having MISSING cog attribute
  discord/commands/core.py
Labels: bug
