Repository Pycord-Development/pycord, pull requests merged in 2022-11, with the labels that each got.

#1758 Update user-agent
  discord/http.py
Labels: priority: high, status: awaiting review

#1760 fix(example): fix incorrect typehint
  examples/modal_dialogs.py
Labels: priority: low, status: awaiting review, examples

#1769 ci: add commitlint workflow
  .github/workflows/pr-deps.yml
Labels: priority: medium, status: awaiting review

#1710 docs: Autodoc typehints
  discord/abc.py
  discord/activity.py
  discord/appinfo.py
  discord/asset.py
  discord/audit_logs.py
  discord/automod.py
  discord/channel.py
  discord/client.py
  discord/cog.py
  discord/colour.py
  discord/commands/context.py
  discord/commands/core.py
  discord/components.py
  discord/emoji.py
  discord/ext/bridge/context.py
  discord/ext/bridge/core.py
  discord/ext/commands/context.py
  discord/ext/commands/core.py
  discord/ext/commands/flags.py
  discord/ext/commands/help.py
  discord/ext/tasks/__init__.py
  discord/gateway.py
  discord/guild.py
  discord/integrations.py
  discord/interactions.py
  discord/invite.py
  discord/member.py
  discord/message.py
  discord/object.py
  discord/partial_emoji.py
  discord/permissions.py
  discord/player.py
  discord/reaction.py
  discord/role.py
  discord/scheduled_events.py
  discord/shard.py
  discord/stage_instance.py
  discord/sticker.py
  discord/team.py
  discord/template.py
  discord/threads.py
  discord/ui/button.py
  discord/ui/input_text.py
  discord/ui/item.py
  discord/ui/modal.py
  discord/ui/select.py
  discord/ui/view.py
  discord/user.py
  discord/voice_client.py
  discord/webhook/async_.py
  discord/webhook/sync.py
  discord/welcome_screen.py
  discord/widget.py
  docs/conf.py
  pyproject.toml
Labels: documentation, priority: medium, status: in progress

#1775 feat: Add support for nsfw commands
  CHANGELOG.md
  discord/bot.py
  discord/commands/core.py
  discord/commands/permissions.py
  discord/ext/bridge/core.py
  docs/api/application_commands.rst
  docs/ext/bridge/api.rst
Labels: priority: low, feature, ext.bridge, upcoming discord feature

#1768 chore(deps): Sort requirements files
  .github/workflows/check.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  pyproject.toml
  requirements/_.txt
  requirements/all.txt
  requirements/dev.txt
  requirements/docs.txt
  requirements/speed.txt
  requirements/voice.txt
Labels: priority: low, status: awaiting review

#1773 docs: Improve toctrees & sidebar formatting
  docs/_static/css/custom.css
  docs/_static/js/custom.js
  docs/ext/bridge/index.rst
  docs/ext/commands/index.rst
  docs/ext/pages/index.rst
  docs/ext/tasks/index.rst
  docs/index.rst
Labels: documentation, priority: low, status: awaiting review

#1636 feat: Complete forum channel implementation
  discord/abc.py
  discord/channel.py
  discord/enums.py
  discord/flags.py
  discord/http.py
  discord/partial_emoji.py
  discord/threads.py
  discord/types/channel.py
  discord/types/threads.py
Labels: priority: high, status: in progress, feature

#1647 refactor: make `ApplicationContext.user` non-optional
  discord/commands/context.py
  discord/interactions.py
Labels: bug, priority: low, status: in progress

#1789 chore: Remove `PRIVATE_THREADS`
  CHANGELOG.md
  discord/guild.py
  discord/types/guild.py
Labels: priority: low

#1802 fix(ext.bridge): fix bridge_commands attribute
  discord/cog.py
  discord/ext/bridge/bot.py
  discord/ext/bridge/core.py
Labels: bug, ext.bridge
