Repository Pycord-Development/pycord, pull requests merged in 2022-02, with the labels that each got.

#895 [ext.pages] Add disable/cancel methods to `Paginator` class
  discord/ext/pages/pagination.py
  examples/views/paginator.py
Labels: priority: low, Merge with squash, pages

#751 Features/voice receive
  .gitignore
  discord/__init__.py
  discord/errors.py
  discord/gateway.py
  discord/opus.py
  discord/sinks/__init__.py
  discord/sinks/core.py
  discord/sinks/errors.py
  discord/sinks/m4a.py
  discord/sinks/mka.py
  discord/sinks/mkv.py
  discord/sinks/mp3.py
  discord/sinks/mp4.py
  discord/sinks/ogg.py
  discord/sinks/pcm.py
  discord/sinks/wave.py
  discord/voice_client.py
  docs/api.rst
  examples/audio_recording.py
Labels: priority: medium, status: in progress, feature, Merge with squash

#759 Command registration rewrite
  discord/bot.py
Labels: help wanted, priority: high, status: in progress, Merge with squash

#908 fix: add sinks to packages
  setup.py
Labels: bypass-review

#919 feat: type hint `Sink.vc`
  discord/sinks/core.py
Labels: priority: low, status: awaiting review, feature, Merge normally

#920 fix: imports
  discord/sinks/core.py
Labels: bypass-review

#924 Update audio_recording.py
  examples/audio_recording.py
Labels: bug, examples

#830 Add `created_at` to `Thread`
  discord/threads.py
Labels: priority: low, status: planned, Merge with squash

#931 Add typing back to actx.author
  discord/commands/context.py
Labels: priority: low, status: awaiting review, Merge normally

#934 Fix typo in `voice_client.py`
  discord/voice_client.py
Labels: documentation, priority: low, status: awaiting review, Merge normally

#938 Use a comment for feature freeze notice
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status: awaiting review, Merge normally

#937 Fix actx.invoke docstring
  discord/commands/context.py
Labels: documentation, status: awaiting review, Merge normally

#941 Fix getting desynced commands
  discord/bot.py
Labels: bug, priority: high, status: awaiting review, Merge normally

#939 Remove unnecessary type conversion
  discord/bot.py
Labels: status: awaiting review, Merge normally

#935 Add `selected_options` and `unselected_options` properties to `ApplicationContext`
  discord/commands/context.py
Labels: priority: medium, status: awaiting review, feature, Merge with squash

#957 Improve and fix command registration
  discord/bot.py
Labels: bug, priority: high, status: awaiting review, Merge with squash

#953 Updates and fixes to `ApplicationContext.selected_options` and `ApplicationContext.unselected_options`
  discord/commands/context.py
Labels: bug, priority: high, status: awaiting review, Merge with squash

#630 Add support for Input Text and Modal components
  discord/bot.py
  discord/components.py
  discord/enums.py
  discord/interactions.py
  discord/state.py
  discord/types/components.py
  discord/ui/__init__.py
  discord/ui/input_text.py
  discord/ui/modal.py
  examples/modal_dialogs.py
Labels: priority: high, status: awaiting review, feature, Merge with squash

#964 Fix circular import in #579
  discord/types/message.py
Labels: bug, priority: high, status: awaiting review, Merge with squash

#579 Slash Attachments
  discord/commands/core.py
  discord/enums.py
  discord/types/interactions.py
  discord/types/message.py
Labels: priority: high, status: awaiting review, feature

#971 Remove interactionsBot example
  examples/interactionsBot/bot.py
  examples/interactionsBot/cog_group/__init__.py
  examples/interactionsBot/cogs/basicSlash_cog.py
  examples/interactionsBot/cogs/button_cog.py
  examples/interactionsBot/cogs/dropdown_cog.py
  examples/interactionsBot/cogs/slashGroup_cog.py
  examples/interactionsBot/cogs/slashOption_cog.py
Labels: priority: high, status: awaiting review, Merge normally, examples

#966 Update `Item` references in modal.py to `InputText`
  discord/ui/modal.py
Labels: documentation, priority: low, status: awaiting review, Merge normally

#965 Add slash command attachment example
  discord/enums.py
  examples/app_commands/slash_options.py
Labels: status: awaiting review, Merge with squash, examples

#988 Modal and InputText updates/fixes
  discord/ui/input_text.py
  discord/ui/modal.py
  examples/modal_dialogs.py
Labels: priority: high, status: awaiting review, Merge with squash

#992 Add modals to docs
  docs/api.rst
Labels: documentation, bypass-review

#995 Move dev requirements to requirements-dev.txt
  requirements-dev.txt
  requirements.txt
Labels: priority: medium, status: awaiting review, dependencies, Merge with squash

#1007 Fix #982
  discord/commands/core.py
Labels: bug

#1012 Bump API to v10
  discord/guild.py
  discord/http.py
Labels: priority: high, status: awaiting review, feature, Merge with squash

#1015 Properly set Black to use 120 characters for line length
  .pre-commit-config.yaml
Labels: priority: high, bypass-review, Merge normally

#1019 Add better linting
  .github/workflows/lint.yaml
  .pre-commit-config.yaml
  docs/conf.py
  docs/extensions/attributetable.py
  docs/extensions/builder.py
  docs/extensions/details.py
  docs/extensions/nitpick_file_ignorer.py
  requirements-dev.txt
  setup.py
Labels: priority: high, bypass-review, Merge with squash

#1014 Add Message Content Intent
  discord/flags.py
Labels: priority: high, status: awaiting review, feature, Merge with squash

#1013 Add `wait()` method to `Modal` class
  discord/ui/modal.py
Labels: status: awaiting review, feature

#1023 Minor Documentation Changes
  docs/installing.rst
  docs/intents.rst
  docs/quickstart.rst
Labels: documentation, priority: medium, status: awaiting review, Merge with squash

#1024 Set force to default true (registration rewrite 2)
  discord/bot.py
Labels: bug, priority: high, status: awaiting review, Merge with squash

#1035 Fix missing .channels wildcard import removed in #1012
  discord/guild.py
Labels: bug, priority: high, bypass-review, Merge normally

#1032 add discord.http.API_VERSION
  discord/__init__.py
  discord/http.py
Labels: priority: medium, status: awaiting review, Merge normally

#1040 Add custom_id attribute to Interaction
  discord/interactions.py
Labels: priority: low, status: awaiting review, feature, Merge normally

#1030 Note message content requirement in `commands.Bot`
  discord/ext/commands/bot.py
Labels: documentation

#1017 Raise TypeError if component custom_id type is not `str`
  discord/components.py
  discord/ui/button.py
  discord/ui/input_text.py
  discord/ui/modal.py
  discord/ui/select.py
Labels: priority: low, status: awaiting review, Merge with squash

#1060 Change custom_id MISSING comparison to `None` for Select class to match other components
  discord/ui/select.py
Labels: bug, priority: high, bypass-review, Merge with squash

#1036 Replace scheduled event imports with wildcard
  discord/__init__.py
Labels: priority: high, status: awaiting review, Merge normally

#1066 Add and update docstrings for `Modal` and `InputText` objects and related methods
  discord/interactions.py
  discord/ui/input_text.py
  discord/ui/modal.py
Labels: documentation, bypass-review, Merge normally

#1072 Remove lint workflow temporarily due to implementation concerns
  .github/workflows/lint.yaml
Labels: bypass-review

#1091 Fix for `InputText.label` being required
  discord/ui/input_text.py
Labels: bypass-review

#1094 Fix for `InputText.value` not being properly cleared for non-required fields
  discord/ui/input_text.py
Labels: bug, priority: high, bypass-review, Merge normally
