Repository Pycord-Development/pycord, pull requests merged in 2022-09, with the labels that each got.

#1534 feat(bot.py): fix type issues
  discord/bot.py
  discord/commands/core.py
Labels: bug, priority: medium, status: in progress, feature

#1620 Revert "enclose in square brackets"
  discord/commands/core.py
  discord/ext/commands/core.py
Labels: priority: medium, status: awaiting review, Merge with squash

#1633 fix(ext.bridge): bridge groups failing
  discord/cog.py
  discord/ext/bridge/core.py
Labels: bug

#1631 fix(ext.bridge): name being passed twice in groups
  discord/ext/bridge/core.py
Labels: bug

#1656 Add 3.11 to package classifiers
  setup.py
Labels: documentation, priority: low, status: awaiting review
