Repository Pycord-Development/pycord, pull requests merged in 2022-12, with the labels that each got.

#1814 fix: Fix attribute error in select
  discord/ui/select.py
Labels: bug, priority: medium, python

#1817 fix: map received applied_tags to int
  CHANGELOG.md
  discord/threads.py
Labels: bug, priority: high, status: awaiting review

#1822 fix: creating automod rules & automod docs
  discord/automod.py
Labels: bug, documentation, priority: high, status: awaiting review

#1823 fix(ext.bridge): fix groups missing parent attr
  CHANGELOG.md
  discord/ext/bridge/core.py
Labels: bug

#1828 fix: Reflect the api for bans
  discord/guild.py
  discord/iterators.py
Labels: priority: medium, API Reflection
