Repository Pycord-Development/pycord, pull requests merged in 2022-06, with the labels that each got.

#1404 The examples link is broken
  docs/conf.py
Labels: bug, documentation, priority: high, Merge with squash, examples

#1395 Fix busy-loop in opus.py DecodeManager
  discord/opus.py
Labels: bug, priority: high, status: awaiting review, Merge with squash

#1365 Fix incorrect activities and permissions on `Interaction` and `Option` objects
  discord/channel.py
  discord/commands/core.py
  discord/flags.py
  discord/guild.py
  discord/interactions.py
Labels: bug, priority: high, status: awaiting review

#1410 Revert "Bump sphinx from 4.5.0 to 5.0.1"
  setup.py
Labels: bug, documentation, priority: high, dependencies, bypass-review

#1389 Update repository examples
  examples/app_commands/context_menus.py
  examples/app_commands/info.py
  examples/app_commands/slash_autocomplete.py
  examples/app_commands/slash_basic.py
  examples/app_commands/slash_cog.py
  examples/app_commands/slash_cog_groups.py
  examples/app_commands/slash_groups.py
  examples/app_commands/slash_options.py
  examples/app_commands/slash_perms.py
  examples/audio_recording.py
  examples/background_task.py
  examples/background_task_asyncio.py
  examples/basic_bot.py
  examples/basic_voice.py
  examples/bridge_commands.py
  examples/converters.py
  examples/cooldown.py
  examples/custom_context.py
  examples/deleted.py
  examples/edits.py
  examples/guessing_game.py
  examples/modal_dialogs.py
  examples/new_member.py
  examples/reaction_roles.py
  examples/reply.py
  examples/secret.py
  examples/timeout.py
  examples/views/button_roles.py
  examples/views/confirm.py
  examples/views/counter.py
  examples/views/dropdown.py
  examples/views/ephemeral.py
  examples/views/link.py
  examples/views/paginator.py
  examples/views/persistent.py
  examples/views/tic_tac_toe.py
  examples/wait_for_event.py
Labels: documentation, priority: low, status: in progress, Merge with squash, examples

#1428 Enum options not setting `input_type` to a SlashCommandOptionType
  discord/commands/core.py
Labels: bug

#1394 Update Activity.buttons documentation
  discord/activity.py
  discord/types/activity.py
Labels: documentation

#1400 Reduces redundancy for 1 or more files
  discord/message.py
Labels: priority: low, status: awaiting review

#1405 Webhooks creating forum posts
  discord/webhook/async_.py
  discord/webhook/sync.py
Labels: feature

#1438 Regular expression changes
  discord/ext/commands/converter.py
  discord/partial_emoji.py
  discord/webhook/async_.py
  discord/webhook/sync.py
Labels: question, priority: low

#1446 Add message property to views
  discord/abc.py
  discord/ui/view.py
Labels: priority: medium, status: awaiting review, feature, Merge with squash

#1411 Add new hooks/handlers to bridge commands
  discord/ext/bridge/core.py
Labels: feature, Merge with squash, ext.bridge

#1435 `Callable` enclose in square brackets
  discord/commands/core.py
  discord/ext/commands/core.py
Labels: question, priority: low

#1454 Cleanup `ext.bridge` docs
  discord/ext/bridge/bot.py
  discord/ext/bridge/context.py
  discord/ext/bridge/core.py
  docs/ext/bridge/index.rst
Labels: documentation, priority: medium, Merge with squash
