Repository Pycord-Development/pycord, pull requests merged in 2023-03, with the labels that each got.

#1955 fix: ip discovery changes (74 byte udp packets)
  CHANGELOG.md
  discord/gateway.py
Labels: bug, priority: high, status: awaiting review, API Reflection

#1960 fix: pass `reason` to the correct method in AutoModRule
  CHANGELOG.md
  discord/guild.py
Labels: bug, status: awaiting review, python

#1975 docs: fix message_content missing subject
  discord/flags.py
Labels: documentation, priority: low, status: awaiting review

#1957 feat!: one time event listeners
  CHANGELOG.md
  discord/client.py
  docs/api/clients.rst
  docs/ext/commands/api.rst
Labels: good first issue, priority: medium, status: awaiting review, feature, python

#1992 feat(ApplicationFlags): add application_auto_moderation_rule_create_badge
  CHANGELOG.md
  discord/flags.py
Labels: priority: low, status: awaiting review, feature, python

#1989 fix: attribute error with listeners in cogs
  CHANGELOG.md
  discord/client.py
Labels: bug, status: awaiting review, feature
