Repository Pycord-Development/pycord, pull requests merged in 2023-06, with the labels that each got.

#2093 chore: cleanup `audio_recording_merged` example
  examples/audio_recording_merged.py
Labels: PA: All Contributors pending

#2092 fix: changelog entry in wrong section
  CHANGELOG.md
Labels: PA: All Contributors pending, PA: Maintainers pending

#2099 fix: command_prefix and help_command typehints
  CHANGELOG.md
  discord/ext/commands/bot.py
Labels: priority: low, status: awaiting review

#2102 feat: add new embedded activities
  CHANGELOG.md
  discord/enums.py
  docs/api/enums.rst
Labels: priority: low, status: awaiting review, feature, python, API Reflection

#2103 revert: #1945
  CHANGELOG.md
  discord/client.py
  docs/api/events.rst
Labels: status: awaiting review

#2104 fix: values access before interaction
  CHANGELOG.md
  discord/ui/select.py
Labels: bug, status: awaiting review

#2108 docs: fix broken link
  discord/commands/options.py
Labels: documentation, priority: low, status: awaiting review

#2091 feat: Add `cooldown` and `max_concurrency` to `SlashCommandGroup`
  CHANGELOG.md
  discord/commands/core.py
Labels: bug, status: awaiting review, feature

#2126 fix: Correct regression from pull #2124
  discord/commands/core.py
Labels: PA: All Contributors pending

#2146 fix: update thread applied tags
  CHANGELOG.md
  discord/threads.py
Labels: bug, priority: high, status: awaiting review

#2148 fix: properly type ApplicationContext.author
  CHANGELOG.md
  discord/commands/context.py
Labels: bug, status: in progress, changelog needed, PA: All Contributors pending

#2156 fix: add missing delete_after parameter
  CHANGELOG.md
  discord/webhook/async_.py
Labels: changelog needed
