Repository Pycord-Development/pycord, pull requests merged in 2023-08, with the labels that each got.

#2191 fix: thread creation payload
  CHANGELOG.md
  discord/http.py
Labels: priority: high, status: awaiting review, API Reflection

#2198 feat: add missing setters for Embed properties
  discord/embeds.py
Labels: bug, PA: All Contributors pending

#2201 fix: #2198
  discord/embeds.py
Labels: PA: All Contributors pending

#2206 feat: add support for custom status
  CHANGELOG.md
  discord/activity.py
Labels: priority: medium, status: awaiting review, feature, API Reflection

#2153 feat: Add `Guild.delete_auto_moderation_rule`
  CHANGELOG.md
  discord/guild.py
Labels: feature, API Reflection, on hold, PA: All Contributors pending

#2220 docs: Update CHANGELOG.md with merged pull request #2164
  CHANGELOG.md
Labels: PA: All Contributors pending
