Repository Pycord-Development/pycord, pull requests merged in 2023-01, with the labels that each got.

#1850 fix: Specify required argument types for variadic functions
  discord/opus.py
Labels: bug, priority: low, status: awaiting review

#1843 docs: New select examples
  examples/views/channel_select.py
  examples/views/role_select.py
Labels: examples

#1859 feat!: add missing embedded activities
  CHANGELOG.md
  discord/enums.py
  docs/api/enums.rst
Labels: priority: medium, status: awaiting review, feature, API Reflection

#1871 chore: Update logos
  docs/images/pycord.ico
  docs/images/pycord_logo.png
Labels: priority: high

#1886 fix: Update release_level parameters
  discord/__main__.py
Labels: priority: high

#1883 fix: Document Option.channel_types and properly support further channel types
  discord/commands/options.py
  discord/enums.py
Labels: documentation, status: awaiting review, feature
