Repository Pycord-Development/pycord, pull requests merged in 2023-02, with the labels that each got.

#1912 feat: add silent messages to MessageFlags
  CHANGELOG.md
  discord/flags.py
Labels: status: awaiting review, feature, python

#1913 feat: add silent parameter to Messageable.send
  CHANGELOG.md
  discord/abc.py
  discord/flags.py
Labels: priority: low, status: awaiting review, feature

#1915 feat: add GIF sticker format
  CHANGELOG.md
  discord/enums.py
  docs/api/enums.rst
Labels: priority: high, status: awaiting review, feature

#1916 feat: Bridge Command Events
  CHANGELOG.md
  discord/ext/bridge/bot.py
  discord/ext/bridge/core.py
  docs/ext/bridge/api.rst
Labels: status: in progress, feature, ext.bridge, python

#1838 fix: SlashCommandGroup.walk_commands() error
  discord/commands/core.py
Labels: documentation, priority: medium, status: awaiting review

#1932 feat: Implement audit log events
  discord/flags.py
  discord/raw_models.py
  discord/state.py
  discord/types/raw_models.py
  docs/api/events.rst
  docs/api/models.rst
  docs/faq.rst
Labels: priority: high, feature, python, API Reflection

#1937 fix(misc): RawAuditLogEntryEvent fixes
  discord/raw_models.py
  discord/types/raw_models.py
Labels: API Reflection

#1907 feat: Move additional event handler functionality to `Client`
  discord/bot.py
  discord/client.py
  docs/api/events.rst
Labels: feature, python

#1928 fix: UnboundLocalError
  discord/ext/bridge/bot.py
Labels: bug, status: awaiting review, changelog needed

#1946 fix: AttributeErrors from event handler move
  discord/cog.py
  discord/ext/commands/bot.py
Labels: bug, priority: high

#1940 feat: add `once` decorator to `discord.Client`
  CHANGELOG.md
  discord/client.py
  docs/api/clients.rst
  docs/api/events.rst
  docs/ext/commands/api.rst
Labels: status: awaiting review, feature, python

#1950 chore(docs): add missing decorator in examples
  docs/ext/commands/commands.rst
Labels: documentation, priority: low, status: awaiting review, examples

#1936 feat: Support for text in stage
  CHANGELOG.md
  discord/abc.py
  discord/channel.py
  discord/message.py
  discord/state.py
Labels: priority: high, status: awaiting review, feature
