Repository Pycord-Development/pycord, pull requests merged in 2023-05, with the labels that each got.

#1922 fix!: Reflect the api for getting bans correctly
  CHANGELOG.md
  discord/guild.py
  discord/iterators.py
Labels: API Reflection

#1984 feat: Add synchronization to start of audio recordings
  CHANGELOG.md
  discord/sinks/core.py
  discord/voice_client.py
  examples/audio_recording_merged.py
Labels: priority: medium, status: awaiting review, feature, undocumented discord feature

#2053 docs: clarify defer's ephemeral arg
  discord/interactions.py
Labels: documentation, priority: low, status: awaiting review, API Reflection

#2044 fix: Restore overriding on_application_command_error via listener
  CHANGELOG.md
  discord/bot.py
Labels: bug, priority: high

#2061 fix: add defaults to __init__s on embed classes
  CHANGELOG.md
  discord/embeds.py
Labels: bug

#2063 refactor!: embed classes
  CHANGELOG.md
  discord/embeds.py
  docs/api/data_classes.rst
Labels: bug, priority: high, status: awaiting review, API Reflection, changelog needed

#1925 fix: KeyError when using method 'individual'
  CHANGELOG.md
  discord/bot.py
Labels: bug, good first issue, priority: medium, status: awaiting review, python

#2042 feat!: pomelo
  discord/abc.py
  discord/enums.py
  discord/ext/commands/converter.py
  discord/guild.py
  discord/member.py
  discord/team.py
  discord/types/user.py
  discord/user.py
  discord/webhook/async_.py
  discord/widget.py
  docs/api/events.rst
  examples/converters.py
Labels: bug, documentation, help wanted, priority: medium, status: planned, feature, upcoming discord feature, undocumented discord feature, API Reflection

#2085 docs(changelog): log username change
  CHANGELOG.md
Labels: documentation, priority: low, status: awaiting review

#2086 feat: Add icon and unicode_emoji to Guild.create_role
  CHANGELOG.md
  discord/guild.py
Labels: priority: medium, status: awaiting review, feature, python, API Reflection

#2087 fix: Adjust default_avatar behavior depending on username
  CHANGELOG.md
  discord/user.py
Labels: status: awaiting review, upcoming discord feature, API Reflection

#2078 fix: channel id might be null
  CHANGELOG.md
  discord/state.py
Labels: bug, priority: high

#2075 fix: creating forum threads with files
  CHANGELOG.md
  discord/channel.py
  discord/http.py
Labels: priority: high, status: awaiting review, feature, API Reflection

#2090 fix: wrong type hint `Sink.vc`
  discord/sinks/core.py
Labels: unconfirmed bug, PA: All Contributors pending
