Repository Pycord-Development/pycord, pull requests merged in 2023-04, with the labels that each got.

#1998 fix(scheduled_events): location editing breaking
  CHANGELOG.md
  discord/scheduled_events.py
Labels: bug, status: awaiting review, API Reflection

#1994 fix: add None support for ClientUser edit
  CHANGELOG.md
  discord/user.py
Labels: bug, status: awaiting review, changelog needed

#2007 docs: fix typo in .send docstring
  discord/abc.py
Labels: documentation

#2014 chore: update file upload size limit
  CHANGELOG.md
  discord/guild.py
Labels: priority: medium, status: awaiting review, python, API Reflection

#2019 chore(docs): revert removal of custom search scoring
  docs/_static/js/scorer.js
  docs/conf.py
Labels: documentation, priority: high

#1999 fix(ext.bridge): Bridge options & bool converter breaking sometimes
  CHANGELOG.md
  discord/ext/bridge/core.py
Labels: bug, status: awaiting review, ext.bridge

#1993 feat: suppress FFMPEG output
  CHANGELOG.md
  discord/sinks/m4a.py
  discord/sinks/mka.py
  discord/sinks/mkv.py
  discord/sinks/mp3.py
  discord/sinks/mp4.py
  discord/sinks/ogg.py
Labels: status: awaiting review, feature, python

#1996 feat: add new parameters to ``discord.Embed``
  CHANGELOG.md
  discord/embeds.py
  docs/api/data_classes.rst
Labels: priority: medium, status: awaiting review, feature, python

#1801 feat: Add possibility to start bot via async context manager
  CHANGELOG.md
  discord/client.py
  examples/basic_async_bot.py
Labels: status: awaiting review, feature

#1997 fix: store message in view when sent using webhook or when message is edited
  CHANGELOG.md
  discord/interactions.py
  discord/message.py
  discord/webhook/async_.py
Labels: bug, priority: medium, status: awaiting review

#1981 fix: webhook message editing on forums missing thread_id
  CHANGELOG.md
  discord/webhook/async_.py
Labels: bug, priority: medium, status: awaiting review, API Reflection, changelog needed

#2016 feat: voice message support
  CHANGELOG.md
  discord/flags.py
  discord/message.py
  discord/permissions.py
  discord/types/message.py
Labels: documentation, priority: medium, status: awaiting review, feature

#2023 feat: Add data attribute to all raw event payloads
  CHANGELOG.md
  discord/raw_models.py
Labels: priority: low, status: awaiting review, feature

#2026 feat: Move ctx.respond to Interaction and implement Interaction.edit
  CHANGELOG.md
  discord/commands/context.py
  discord/interactions.py
Labels: priority: medium, feature

#2025 feat: Received Interactions come with a channel object
  CHANGELOG.md
  discord/channel.py
  discord/interactions.py
  discord/types/interactions.py
Labels: priority: medium, feature

#2030 fix: Improve Automod compatibility with Audit Logs + minor fixes
  CHANGELOG.md
  discord/audit_logs.py
  discord/automod.py
  discord/enums.py
  discord/types/audit_log.py
  docs/api/enums.rst
Labels: status: awaiting review, feature

#2034 docs: update thread edit docs
  discord/threads.py
Labels: documentation, priority: low, status: awaiting review
