Repository Pycord-Development/pycord, pull requests merged in 2023-07, with the labels that each got.

#2158 refactor: Remove un-needed logic in EqualityComparable.__ne__
  discord/mixins.py
Labels: PA: All Contributors pending

#2162 fix: `ScheduledEvent.creator_id` returning incorrect type
  CHANGELOG.md
  discord/scheduled_events.py
Labels: bug, status: awaiting review, python

#2171 feat: add creator monetization-related audit log action types
  CHANGELOG.md
  discord/enums.py
  docs/api/enums.rst
Labels: priority: medium, status: awaiting review, python, API Reflection

#2170 refactor: replace orjson support with msgspec
  CHANGELOG.md
  README.rst
  discord/utils.py
  requirements/speed.txt
Labels: dependencies

#2182 feat(actions): version-updates.yml
  .github/workflows/version-updates.yml
Labels: github_actions, PA: All Contributors pending, PA: Maintainers pending
