Repository Pycord-Development/pycord, pull requests merged in 2023-12, with the labels that each got.

#2243 fix: attribute error in command serialization
  CHANGELOG.md
  discord/commands/core.py
  tests/test_typing_annotated.py
Labels: bug, priority: medium, status: awaiting review

#2257 fix: `Intents.all` returning the wrong value
  CHANGELOG.md
  discord/flags.py
Labels: bug

#2274 fix: update typed dicts for commands
  discord/bot.py
  discord/types/interactions.py
Labels: priority: low, status: awaiting review, API Reflection

#2178 feat: ForumChannel default_reaction_emoji attribute
  CHANGELOG.md
  discord/abc.py
  discord/channel.py
  discord/guild.py
  discord/http.py
  discord/partial_emoji.py
Labels: feature

#2292 feat: support python 3.12
  .github/workflows/check.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  pyproject.toml
Labels: priority: low, github_actions, python

#2295 fix: auditlogs after param for fetch is ignored
  CHANGELOG.md
  discord/iterators.py
Labels: bug, priority: medium

#2297 fix: handle ephemeral messages in `disable_on_timeout`
  discord/ui/view.py
Labels: bug

#2301 fix: `AttributeError` when failing to establish initial websocket connection
  CHANGELOG.md
  discord/client.py
Labels: bug, python
