Repository Pycord-Development/pycord, pull requests merged in 2023-11, with the labels that each got.

#2255 fix: TypeErrors raised from Reaction events
  discord/raw_models.py
Labels: priority: high

#2196 fix: tasks loop infinitely when `tzinfo` is neither `None` nor UTC
  CHANGELOG.md
  discord/ext/tasks/__init__.py
Labels: bug, status: awaiting review, python

#2112 feat: Add slowmode_delay attribute to discord.VoiceChannel
  CHANGELOG.md
  discord/channel.py
Labels: priority: low, status: in progress, feature, API Reflection, on hold

#2271 fix: offset-aware time when preparing tasks
  CHANGELOG.md
  discord/ext/tasks/__init__.py
Labels: bug, priority: medium, status: awaiting review
