Repository Pycord-Development/pycord, pull requests merged in 2024-12, with the labels that each got.

#2609 chore: add support for Python 3.13
  .github/workflows/docs-checks.yml
  .github/workflows/docs-localization-download.yml
  .github/workflows/docs-localization-upload.yml
  .github/workflows/lib-checks.yml
  .github/workflows/release.yml
  .readthedocs.yml
  README.rst
  docs/installing.rst
  pyproject.toml
  requirements/dev.txt
Labels: priority: high, feature, python

#2673 docs: changelog grammar edits
  CHANGELOG.md
Labels: documentation, priority: low

#2659 feat: Add helper methods to determine interactions integrations
  CHANGELOG.md
  discord/commands/context.py
  discord/interactions.py
Labels: feature

#2579 feat: Voice Message Sending
  CHANGELOG.md
  discord/abc.py
  discord/file.py
  discord/http.py
  discord/interactions.py
  discord/webhook/async_.py
Labels: priority: medium, feature, API Reflection

#2679 fix: Fixed Attachment Metadata Being Set Incorrectly In Interaction Responses
  CHANGELOG.md
  discord/webhook/async_.py
Labels: bug, priority: high, status: awaiting review

#2683 docs: add detailed docstrings to properties of Item
  discord/ui/item.py
Labels: PA: All Contributors pending
