Repository Pycord-Development/pycord, pull requests merged in 2024-06, with the labels that each got.

#2457 fix: Overall type-hinting improvements
  CHANGELOG.md
  discord/abc.py
  discord/audit_logs.py
  discord/channel.py
  discord/commands/context.py
  discord/commands/core.py
  discord/context_managers.py
  discord/ext/commands/converter.py
  discord/ext/commands/help.py
  discord/guild.py
  discord/http.py
  discord/interactions.py
  discord/invite.py
  discord/member.py
  discord/message.py
  discord/partial_emoji.py
  discord/raw_models.py
  discord/reaction.py
  discord/sinks/core.py
  discord/state.py
  discord/types/channel.py
  discord/types/message.py
  discord/types/onboarding.py
  discord/types/webhook.py
  discord/user.py
  discord/voice_client.py
  discord/webhook/async_.py
Labels: bug, priority: low, status: in progress, PA: All Contributors pending

#2408 feat: Polls
  CHANGELOG.md
  discord/__init__.py
  discord/abc.py
  discord/client.py
  discord/enums.py
  discord/flags.py
  discord/http.py
  discord/interactions.py
  discord/iterators.py
  discord/message.py
  discord/permissions.py
  discord/poll.py
  discord/raw_models.py
  discord/state.py
  discord/types/message.py
  discord/types/poll.py
  discord/types/raw_models.py
  discord/webhook/async_.py
  docs/api/data_classes.rst
  docs/api/enums.rst
  docs/api/events.rst
Labels: priority: medium, status: awaiting review, feature

#2464 fix: options initializing with null input type
  CHANGELOG.md
  discord/commands/options.py
Labels: PA: All Contributors pending, PA: Maintainers pending

#2409 feat: user-installable apps
  CHANGELOG.md
  discord/bot.py
  discord/commands/core.py
  discord/commands/permissions.py
  discord/enums.py
  discord/interactions.py
  discord/message.py
  discord/permissions.py
  discord/types/interactions.py
  discord/types/message.py
  docs/api/enums.rst
  docs/api/models.rst
  examples/app_commands/slash_users.py
Labels: priority: medium, status: awaiting review, feature, upcoming discord feature

#2462 docs: limits on integer and number option types
  docs/api/enums.rst
Labels: documentation

#2438 feat: update monetization
  CHANGELOG.md
  discord/client.py
  discord/components.py
  discord/enums.py
  discord/guild.py
  discord/http.py
  discord/interactions.py
  discord/iterators.py
  discord/monetization.py
  discord/types/components.py
  discord/ui/button.py
  discord/user.py
  docs/api/enums.rst
Labels: bug, priority: low, status: awaiting review, feature, upcoming discord feature
