Repository Pycord-Development/pycord, pull requests merged in 2024-01, with the labels that each got.

#2303 fix: change default attribute of `SlashCommandGroup`
  CHANGELOG.md
  discord/commands/core.py
Labels: bug, priority: high, status: in progress

#2326 chore: allow versions of aiohttp that are non-breaking forever
  requirements/_.txt
Labels: dependencies

#2327 fix: parse options
  discord/bot.py
  discord/commands/core.py
Labels: bug, priority: high, status: awaiting review

#2330 fix: parse options again after setting cog
  discord/commands/core.py
Labels: bug, priority: high, status: awaiting review

#2299 fix: `AttributeError` when comparing commands
  CHANGELOG.md
  discord/commands/core.py
Labels: bug, priority: high, status: awaiting review

#2252 chore(bridge): use BridgeOption instead of Option
  CHANGELOG.md
  discord/ext/bridge/core.py
  docs/ext/bridge/api.rst
Labels: priority: low, status: awaiting review

#2332 fix: slash options broken when declared explicitly
  CHANGELOG.md
  discord/commands/core.py
Labels: bug, priority: high, status: awaiting review

#2333 fix: setting options using default syntax makes option optional
  CHANGELOG.md
  discord/commands/core.py
Labels: bug, priority: low, status: awaiting review

#2337 fix: skip BridgeContext when parsing options
  CHANGELOG.md
  discord/enums.py
Labels: bug, priority: high, status: awaiting review

#2131 feat: implement Avatar Decorations
  CHANGELOG.md
  discord/asset.py
  discord/user.py
Labels: feature, API Reflection

#2127 feat: Implement Onboarding features
  CHANGELOG.md
  discord/__init__.py
  discord/enums.py
  discord/guild.py
  discord/http.py
  discord/onboarding.py
  discord/types/onboarding.py
  docs/api/enums.rst
  docs/api/models.rst
Labels: priority: medium, feature, changelog needed
