Repository Pycord-Development/pycord, pull requests merged in 2024-07, with the labels that each got.

#2463 fix: enum option issues
  CHANGELOG.md
  discord/commands/options.py
Labels: documentation needed

#2488 feat: implement MessageCall
  CHANGELOG.md
  discord/message.py
  discord/types/message.py
  docs/api/data_classes.rst
Labels: PA: All Contributors pending, PA: Maintainers pending

#2480 fix: remove_application_command missing case
  CHANGELOG.md
  discord/bot.py
  discord/commands/core.py
Labels: bug, priority: high, status: awaiting review

#2490 fix: premium buttons and entitlement iterator
  CHANGELOG.md
  discord/client.py
  discord/guild.py
  discord/http.py
  discord/ui/button.py
  discord/user.py
Labels: bug, priority: high, status: in progress

#2371 fix: audit log filtering & sorting
  CHANGELOG.md
  discord/guild.py
  discord/iterators.py
Labels: bug, help wanted, priority: high, API Reflection

#2491 chore: remove `vanity_code` from `Guild.edit`
  CHANGELOG.md
  discord/guild.py
  discord/http.py
Labels: priority: low, status: awaiting review, API Reflection

#2492 fix: further address audit log issues
  CHANGELOG.md
  discord/http.py
  discord/iterators.py
Labels: bug, priority: high, status: awaiting review

#2275 chore: improve nesting error message
  CHANGELOG.md
  discord/commands/core.py
Labels: priority: low, status: awaiting review

#2493 chore: update readme and changelog
  CHANGELOG.md
  README.rst
Labels: priority: low, status: awaiting review, PA: All Contributors pending

#2495 docs: add docs for Interaction.entitlements
  discord/interactions.py
Labels: documentation, priority: high, status: awaiting review
