Repository Pycord-Development/pycord, pull requests merged in 2024-04, with the labels that each got.

#2412 fix: Added member data to the raw_reaction_remove event
  CHANGELOG.md
  discord/raw_models.py
  discord/state.py
Labels: priority: low, status: awaiting review, feature

#2424 docs: remove false optional
  discord/guild.py
Labels: documentation, priority: low, status: awaiting review

#2419 fix: Guild.query_members may accept empty query and limit
  CHANGELOG.md
  discord/guild.py
Labels: status: awaiting review, feature, API Reflection, changelog needed

#2421 feat: Support bulk banning in guilds
  CHANGELOG.md
  discord/guild.py
  discord/http.py
  discord/member.py
  discord/types/guild.py
  docs/ext/commands/commands.rst
Labels: priority: low, status: awaiting review, feature

#2440 fix: type-hinting in Guild.bulk_ban
  discord/guild.py
Labels: PA: All Contributors pending
