Repository Pycord-Development/pycord, pull requests merged in 2024-02, with the labels that each got.

#2273 feat: implement monetization
  CHANGELOG.md
  discord/__init__.py
  discord/client.py
  discord/enums.py
  discord/flags.py
  discord/guild.py
  discord/http.py
  discord/interactions.py
  discord/monetization.py
  discord/state.py
  discord/types/interactions.py
  discord/types/monetization.py
  discord/user.py
  docs/api/data_classes.rst
  docs/api/enums.rst
  docs/api/events.rst
  docs/api/models.rst
Labels: priority: low, status: awaiting review, feature

#2343 fix: `(Sync)WebhookMessage._thread_id` could be `None`
  CHANGELOG.md
  discord/webhook/async_.py
  discord/webhook/sync.py
Labels: bug, priority: high, status: awaiting review

#2341 chore: clean up changelog
  CHANGELOG.md
Labels: documentation, priority: low, status: in progress

#2345 fix: add `entitlements` to slots of `Interaction`
  CHANGELOG.md
  discord/interactions.py
Labels: bug, priority: high, status: awaiting review

#2364 fix: type hint kwargs properly
  CHANGELOG.md
  discord/ext/bridge/core.py
Labels: bug, priority: high, status: awaiting review

#2370 feat: Message.enforce_nonce
  CHANGELOG.md
  discord/abc.py
  discord/http.py
  discord/message.py
  discord/types/message.py
Labels: priority: low, status: awaiting review, feature
