Repository Pycord-Development/pycord, pull requests merged in 2024-09, with the labels that each got.

#2520 feat: add missing AppInfo attributes
  CHANGELOG.md
  discord/appinfo.py
  discord/types/appinfo.py
  docs/api/application_info.rst
Labels: priority: low, status: awaiting review, API Reflection, python

#2568 fix: allow PartialMessage to have PartialMessageable as a channel
  CHANGELOG.md
  discord/message.py
Labels: bug, priority: high

#2573 fix: user context command members having a `None` guild
  CHANGELOG.md
  discord/commands/core.py
Labels: bug, priority: low

#2583 docs: update changelog to be consistent
  CHANGELOG.md
Labels: documentation

#2581 fix: make FFmpegOpusAudio codec behave as docs suggest
  CHANGELOG.md
  discord/player.py
Labels: bug, priority: medium, status: awaiting review

#2584 fix: audio plays in fast forward for first few seconds
  CHANGELOG.md
  discord/player.py
Labels: priority: medium, status: awaiting review, python

#2590 feat: Add optional filter parameter to utils.basic_autocomplete
  CHANGELOG.md
  discord/utils.py
Labels: feature
