Repository Pycord-Development/pycord, pull requests merged in 2024-11, with the labels that each got.

#2615 feat: add missing with_counts parameter to fetch_guilds method
  CHANGELOG.md
  discord/client.py
  discord/http.py
  discord/iterators.py
Labels: priority: low, status: awaiting review, feature, API Reflection

#2620 feat: :sparkles: Add missing soundboard and monetization permissions
  CHANGELOG.md
  discord/permissions.py
Labels: priority: medium, status: awaiting review, feature

#2638 docs: :memo: Add timeout time to `View` docstring
  discord/ui/view.py
Labels: PA: All Contributors pending

#2624 fix: sending polls with PartialWebhook
  CHANGELOG.md
  discord/webhook/async_.py
Labels: priority: medium, status: awaiting review, API Reflection, python

#2639 fix: add missing channel type 16
  discord/enums.py
  discord/types/channel.py
Labels: PA: All Contributors pending

#2653 docs: :memo: Better documentation for latency properties
  discord/client.py
  discord/gateway.py
  discord/shard.py
Labels: PA: All Contributors pending
