Repository Pycord-Development/pycord, pull requests merged in 2024-10, with the labels that each got.

#2596 fix: add Member import for typehinting
  discord/bot.py
Labels: bug, priority: high, status: awaiting review

#2594 fix: don't try to do an interaction_check if there isn't a user available to check
  CHANGELOG.md
  discord/ext/pages/pagination.py
Labels: bug, status: in progress

#2604 docs: Add missing error for Message.edit
  discord/message.py
Labels: PA: All Contributors pending

#2176 refactor: python implementation of `audioop.mul`
  CHANGELOG.md
  discord/player.py
Labels: priority: low

#2618 fix: prevent unclosed client session / unclosed connector
  discord/client.py
Labels: PA: All Contributors pending

#2619 docs: fix minor changelog grammar and wording
  CHANGELOG.md
Labels: priority: low

#2632 fix: handle improper 1000 closures by discord
  discord/gateway.py
Labels: PA: All Contributors pending

#2630 docs: :memo: Add `@bridge_option` to docs
  docs/ext/bridge/api.rst
Labels: PA: All Contributors pending

#2611 fix: :bug: Union type cannot be used in `ctx`.
  CHANGELOG.md
  discord/commands/options.py
Labels: priority: medium, PA: All Contributors pending, python

#2628 fix: TypeError when adding skus to entitlements() method
  CHANGELOG.md
  discord/http.py
Labels: bug, priority: medium, status: awaiting review
