Repository Pycord-Development/pycord, pull requests merged in 2024-08, with the labels that each got.

#2512 fix: :memo: Improve wording in `option` decorator slightly
  discord/commands/options.py
  discord/ext/bridge/core.py
Labels: PA: All Contributors pending

#2521 chore(python)!: remove support for python 3.8
  .flake8
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/test.yml
  .readthedocs.yml
  CHANGELOG.md
  README.rst
  pyproject.toml
Labels: PA: All Contributors pending

#2528 feat: implement `Guild.fetch_role`
  CHANGELOG.md
  discord/guild.py
  discord/http.py
Labels: priority: medium, status: awaiting review, feature, upcoming discord feature, API Reflection

#2530 chore: do something precommit
  .github/workflows/.cleanup-todo
  docs/conf.py
  requirements/docs.txt
Labels: PA: All Contributors pending

#2547 chore(actions)!: rework actions
  .github/workflows/.cleanup-todo
  .github/workflows/check.yml
  .github/workflows/codeql.yml
  .github/workflows/docs-checks.yml
  .github/workflows/docs-localization-download.yml
  .github/workflows/docs-localization-upload.yml
  .github/workflows/lib-checks.yml
  .github/workflows/lint.yml
  .github/workflows/pr-auto-approve.yml
  .github/workflows/pr-checks.yml
  .github/workflows/test.yml
  .github/workflows/todo-checks.yml
  .github/workflows/todo.yml
  .pre-commit-config.yaml
Labels: priority: high, dependencies, PA: All Contributors pending

#2553 fix: empty commit
  docs/conf.py
Labels: PA: All Contributors pending

#2555 fix: EntitlementIterator behavior and type-hinting
  CHANGELOG.md
  discord/iterators.py
Labels: bug

#2556 feat: Member.display_banner
  CHANGELOG.md
  discord/asset.py
  discord/member.py
  discord/types/member.py
Labels: feature

#2500 fix: Missing slots attributes, wrong variable type, duplicate http methods
  CHANGELOG.md
  discord/channel.py
  discord/http.py
  discord/raw_models.py
  discord/state.py
  discord/utils.py
Labels: priority: medium, API Reflection, python
