Repository Pycord-Development/pycord, pull requests merged in 2024-03, with the labels that each got.

#2373 feat: audit logs for voice channel status
  CHANGELOG.md
  discord/enums.py
  discord/types/audit_log.py
Labels: priority: high, status: in progress, feature

#2374 docs: add missing docs for voice channel status audit log
  docs/api/audit_logs.rst
  docs/api/enums.rst
Labels: documentation

#2376 fix: correct `enforce_nonce` implementation
  CHANGELOG.md
  discord/abc.py
  discord/message.py
  discord/types/message.py
Labels: PA: All Contributors pending

#2392 fix: Replace deprecated pkg_resources with importlib.metadata to clear DeprecationWarning
  CHANGELOG.md
  discord/__main__.py
Labels: status: awaiting review

#2396 feat: add `banner` to `ClientUser.edit`
  CHANGELOG.md
  discord/user.py
Labels: changelog needed

#2390 fix: add user argument to paginator.edit
  CHANGELOG.md
  discord/ext/pages/pagination.py
Labels: bug, feature

#2401 docs: fix typo
  discord/bot.py
Labels: documentation, priority: low

#2395 feat: retry http requests that fail with a 503 status
  CHANGELOG.md
  discord/http.py
Labels: status: awaiting review, feature

#2403 feat: add once kwarg to Cog.listener
  discord/cog.py
Labels: changelog needed

#2411 fix: pass proper state to interaction._guild
  CHANGELOG.md
  discord/interactions.py
Labels: changelog needed
