Repository Pycord-Development/pycord, pull requests merged in 2025-05, with the labels that each got.

#2779 fix: webhook/interaction editing with attachments param
  CHANGELOG.md
  discord/webhook/async_.py
Labels: bug, priority: high

#2598 feat: message forwarding
  CHANGELOG.md
  discord/abc.py
  discord/channel.py
  discord/enums.py
  discord/ext/commands/context.py
  discord/flags.py
  discord/message.py
  discord/types/embed.py
  discord/types/message.py
Labels: priority: medium, feature, API reflection, python

#2795 fix: Role Edit TypeHint
  discord/role.py
Labels: PA: All Contributors pending
