Repository Pycord-Development/pycord, pull requests merged in 2025-01, with the labels that each got.

#2621 refactor: :recycle: Use `typing_extensions` instead of `_typed_dict`
  discord/_typed_dict.py
  discord/_version.py
  discord/types/activity.py
  discord/types/appinfo.py
  discord/types/application_role_connection.py
  discord/types/audit_log.py
  discord/types/automod.py
  discord/types/channel.py
  discord/types/components.py
  discord/types/embed.py
  discord/types/guild.py
  discord/types/integration.py
  discord/types/interactions.py
  discord/types/invite.py
  discord/types/message.py
  discord/types/monetization.py
  discord/types/onboarding.py
  discord/types/poll.py
  discord/types/raw_models.py
  discord/types/role.py
  discord/types/sticker.py
  discord/types/threads.py
  discord/types/voice.py
  discord/types/webhook.py
  discord/types/widget.py
  requirements/_.txt
Labels: priority: low, status: awaiting review, dependencies

#2606 feat: ✨ New role tags
  CHANGELOG.md
  discord/role.py
Labels: documentation, priority: medium, status: in progress, feature, API Reflection

#2700 fix: reset exponential backoff after task runs successfully in tasks extension
  CHANGELOG.md
  discord/ext/tasks/__init__.py
Labels: priority: medium, python

#2564 feat: subscriptions & related changes
  CHANGELOG.md
  discord/client.py
  discord/enums.py
  discord/http.py
  discord/iterators.py
  discord/monetization.py
  discord/state.py
  discord/types/monetization.py
  docs/api/enums.rst
  docs/api/events.rst
  docs/api/models.rst
Labels: bug, documentation, priority: low, status: awaiting review, feature
