Repository Pycord-Development/pycord, pull requests merged in 2025-02, with the labels that each got.

#2704 fix: :ambulance: Fix circular import - oops
  discord/ext/commands/help.py
Labels: PA: All Contributors pending

#2709 fix: Allow renewal_sku_ids To Handle None
  CHANGELOG.md
  discord/monetization.py
Labels: PA: All Contributors pending, PA: Maintainers pending

#2666 feat: add support for Python 3.13
  .github/workflows/docs-checks.yml
  .github/workflows/docs-localization-download.yml
  .github/workflows/docs-localization-upload.yml
  .github/workflows/lib-checks.yml
  .github/workflows/release.yml
  .readthedocs.yml
  README.rst
  docs/installing.rst
  pyproject.toml
  requirements/dev.txt
Labels: priority: medium, status: in progress, dependencies, branch: master, on hold, PA: All Contributors pending

#2714 feat: :sparkles: Allow changing base url with `Route.API_BASE_URL`
  CHANGELOG.md
  discord/http.py
Labels: PA: All Contributors pending

#2718 fix: raise intended exception for ephemeral paginator with >=15min timeout
  discord/ext/pages/pagination.py
Labels: PA: All Contributors pending
