Repository Pycord-Development/pycord, pull requests merged in 2025-09, with the labels that each got.

#2780 feat: :sparkles: Parse data as message in `parse_message_update` instead of using `_update`
  CHANGELOG.md
  discord/message.py
  discord/raw_models.py
  discord/state.py
Labels: PA: All Contributors pending

#2711 feat: Implement with_response For Interaction Callbacks
  CHANGELOG.md
  discord/interactions.py
  discord/types/interactions.py
  discord/webhook/async_.py
  docs/api/models.rst
Labels: PA: All Contributors pending, PA: Maintainers pending

#2917 fix: typehint issue
  discord/role.py
Labels: on hold, hold: testing
