Repository Pycord-Development/pycord, pull requests merged in 2025-08, with the labels that each got.

#2843 fix: :bug: Fix missing self. attribution in File component
  CHANGELOG.md
  discord/ui/file.py
Labels: PA: All Contributors pending

#2842 fix: :bug: Fix issue in cv2 example
  examples/views/new_components.py
Labels: PA: All Contributors pending

#2832 docs: :memo: update docstrings for Asset and Attachment classes to clarify hash return values
  discord/asset.py
  discord/message.py
Labels: PA: All Contributors pending, PA: Maintainers pending

#2835 fix: :bug: Issue in `@option` where some annotations could not be used along with `channel_types`
  CHANGELOG.md
  discord/commands/options.py
Labels: PA: All Contributors pending

#2775 feat: allow conversion to Member in MentionableConverter
  CHANGELOG.md
  discord/ext/bridge/core.py
Labels: PA: All Contributors pending

#2672 feat: :sparkles: Add missing feature flags to `Guild.edit`
  CHANGELOG.md
  discord/guild.py
  discord/types/guild.py
Labels: PA: All Contributors pending

#2818 feat: ✨ Add support for role gradient colors in Role
  CHANGELOG.md
  discord/guild.py
  discord/http.py
  discord/role.py
  discord/types/guild.py
  discord/types/role.py
  docs/api/models.rst
Labels: PA: All Contributors pending

#2817 feat: :sparkles: add Nameplate class and integration
  CHANGELOG.md
  discord/__init__.py
  discord/collectibles.py
  discord/types/collectibles.py
  discord/user.py
  docs/api/models.rst
Labels: PA: All Contributors pending, PA: Maintainers pending

#2815 feat: Added support for emoji aliases like `:smile:` in PartialEmoji.from_str (redo)
  CHANGELOG.md
  MANIFEST.in
  discord/emojis.json
  discord/ext/commands/converter.py
  discord/partial_emoji.py
  discord/utils.py
Labels: PA: All Contributors pending

#2876 feat: Add support for user.primary_guild
  CHANGELOG.md
  discord/asset.py
  discord/primary_guild.py
  discord/types/primary_guild.py
  discord/user.py
Labels: priority: high, status: awaiting review, feature

#2872 feat: Message pin updates
  CHANGELOG.md
  discord/abc.py
  discord/http.py
  discord/iterators.py
  discord/message.py
  discord/permissions.py
  discord/types/message.py
Labels: API reflection

#2772 feat: adding missing parameters and attribute documentation
  CHANGELOG.md
  discord/channel.py
  discord/guild.py
Labels: PA: Maintainers pending

#2623 feat: :sparkles: Soundboard
  CHANGELOG.md
  discord/__init__.py
  discord/asset.py
  discord/channel.py
  discord/client.py
  discord/enums.py
  discord/gateway.py
  discord/guild.py
  discord/http.py
  discord/raw_models.py
  discord/soundboard.py
  discord/state.py
  discord/types/channel.py
  discord/types/guild.py
  discord/types/soundboard.py
  discord/utils.py
  docs/api/enums.rst
  docs/api/events.rst
  docs/api/models.rst
  examples/soundboard.py
  requirements/_.txt
Labels: API reflection, PA: All Contributors pending, PA: Maintainers pending

#2852 fix: handling of Optional[...] in command option type resolution
  CHANGELOG.md
  discord/commands/options.py
Labels: PA: All Contributors pending, PA: Maintainers pending

#2892 docs: 📝 Fixes
  discord/channel.py
  discord/client.py
  discord/components.py
  discord/ext/bridge/core.py
  discord/ext/commands/core.py
  discord/guild.py
  discord/raw_models.py
  docs/api/data_classes.rst
  docs/api/enums.rst
  docs/api/events.rst
  docs/api/models.rst
  docs/conf.py
  docs/ext/bridge/api.rst
Labels: documentation

#2893 fix: improve handling of types in option input_type validation
  discord/commands/options.py
Labels: bug
